### ISSUE TITLE
Data Type Preparation for a custom Data set

### ISSUE THREAD

**Issue by kadimaolivier** [facebookresearch/PyTorch-BigGraph#101]
Hi,

Let assume in my data set i have different type of structure

kindly find a structure of my data set:

albert_schwartz	birthplace	chicago
albert_schwartz	deathplace	los_angeles
albert_schwartz	name	albert_schwartz
albert_schwartz	nationality	united_states
albert_schwartz	http//www.w3.org/1999/02/22-rdf-syntax-ns#type	http//dbpedia.org/ontology/Swimmer
bill_tuttle_(swimmer)	birthplace	chicago
bill_tuttle_(swimmer)	deathplace	los_angeles
bill_tuttle_(swimmer)	name	bill_tuttle
bill_tuttle_(swimmer)	name	william_jeremiah_tuttle
bill_tuttle_(swimmer)	nationality	united_states
bill_tuttle_(swimmer)	http//www.w3.org/1999/02/22-rdf-syntax-ns#type	http//dbpedia.org/ontology/Swimmer
jacqueline_alex	birthplace	zwickau
jacqueline_alex	http//www.w3.org/1999/02/22-rdf-syntax-ns#type	http//dbpedia.org/ontology/Swimmer
jade_edmistone	birthplace	brisbane
jade_edmistone	name	jade_edmistone
jade_edmistone	nationality	australia
jade_edmistone	http//www.w3.org/1999/02/22-rdf-syntax-ns#type	http//dbpedia.org/ontology/Swimmer

**anaother structure:**

Paris    islocatedin      France
Paris    Population      2.140.000
paris    type                city

**Questions**

- For my Data preparation:  
Do i have to declare my entities type and relations type somewhere so that PBG will regonise the type of my instances( entities & relations type?)? if yes how and where should i declare that?
or PBG will automaticaly regonise  itself the type of my instance (entites and relations  type)  after lauching the following command: torchbiggraph_import_from_tsv \
>   --lhs-col=0 --rel-col=1 --rhs-col=2 \
>  config.py \
>  data/LAKE/DB_Lake.db2013.txt 

## Observed Results

After getting my embeddings and calculate the euclidean distance between my embeddings 

when i am trying to compare the simularity between instances, for example : 3 instances 
i have obeserved that after calculating the euclidean distance of my embeddings and compare the simularity  between instances in order to  find out which instances are more close to each other  ,i have noticed that from my embeddings 2 instances that are sharing three simulare description(eg: birthplace,deathplace and nationality) these instance has a huge euclidean distance between them while 1 instance who is sharing only one discription with another instance (eg: birthplace ) will be more close meaning the  euclideance distance with another instance that are only sharing one description is small.

base on the above results may you please explain to me what could be the reason ....

Looking forward

kind regards

Olivier

**Comment by lerks** [comment]
In the configuration file you will notice that there are two fields, `entities` and `relations`, which are used to describe the types of entities and relations. Entity types are specified as a dictionary, and the identifier for each entity type is the key with which it appears in this dictionary. Relation types are a list, and are identified by their `name` field. As an example, consider this config describing the reactions of users to movies in an imaginary streaming service:
```
entities = {
    "users": {num_partitions: 10},
    "movies": {num_partitions: 4}
},
relations = [
    {"lhs": "users": "rhs": "movies", "name": "likes"},
    {"lhs": "users": "rhs": "movies", "name": "dislikes"}
]
```

`import_from_tsv` works in 3 possible ways:
- if you don't specify `--rel-col` then it will just implicitly assume that every line in your file describes an edge of the first relation type (in the example above, it would be `likes`). This allows you to work with lists of edges that don't have a type column (see #97).
- if you specify `--rel-col` but your config does _not_ specify `dynamic_relations=True`, then for each edge PBG will take the value in that column and search for a relation type with that `name`, and will consider that the edge is of that type.
- if you specify `--rel-col` but also have `dynamic_relations=True`, your config must only have one relation type, which PBG will use as a "template"; what this means is that PBG will look into the edge file for all the distinct values that appear in the column you specify, and for each of those distinct value it implicitly creates a distinct relation type, "copying" the (one) type you specified in the config (this is what is done in FB15k, although it's considered advanced usage).

**Comment by kadimaolivier** [comment]
Thank you very much for your support , i really appreiciate and many thanks  to you and  to your team for such a great tool "PBG' ...

sincerely 

Olivier KADIMA
