### ISSUE TITLE
How to train embedding  for multiple entities?

### ISSUE THREAD

**Issue by yxleung** [facebookresearch/PyTorch-BigGraph#106]
How can I train embedding with 3 entities? I saw the example with only 2 entities and multiple relationships. But I want to train 3 entities like:

training data format:
A rel-01 B
A rel-02 C
B rel-03 C

A,B,C is entity; rel-01,rel-02,rel-03 is relation;

Looking forward to your reply.

**Comment by lerks** [comment]
If I understand your question correctly, you can achieve this with the following config:
```
"entities": {
    "A": {"num_partitions": 42},
    "B": {"num_partitions": 42},
    "C": {"num_partitions": 42}
},
"relations": [
    {"name": "rel-01", "lhs": "A", "rhs": "B"},
    {"name": "rel-02", "lhs": "A", "rhs": "C"},
    {"name": "rel-03", "lhs": "B", "rhs": "C"}
]
```
I hope this is what you were looking for! (Of course, replace 42 with the appropriate value for your use case)

**Comment by lerks** [comment]
No follow-up for several weeks, I'm assuming the answer was satisfactory, I'm closing the issue.
