### ISSUE TITLE
Questions on how does PBG works on instances type Declaration

### ISSUE THREAD

**Issue by kadimaolivier** [facebookresearch/PyTorch-BigGraph#107]
Hi, i have few questions on How does PBG works on instances type declaration:

For the types of instances,here  is an example:

albert_schwartz   name            albert_schwartz
albert_schwartz   nationality      United_States
albert_schwartz    http://www.w3.org/1999/02/22-rdf-syntax-ns#type        http://dbpedia.org/ontology/Swimmer

In this example, we have 3 triplets concerning a person. The question that arises is ,
Does PBG considers the 3 properties, 1) name 2) nationality 3) http://www.w3.org/1999/02/22-rdf-syntax-ns#type such as properties of the same level or PBG is able to understand that this property type http://www.w3.org/1999/02/22-rdf-syntax-ns#type is different from the other ones (name and nationality )and it  is universal way used to describe the type of instances (as it is done by most of the  tools in the semantic web whereby the  type of instance must be declared)?

Thanking you in advance for your clarification and support

**Comment by kadimaolivier** [comment]
The main goal  i am trying to achieve is finding **similarities between instances of the same type**.

Let assume i have a dataset with instances of different types, for example, instances of the following classes: person, city, country, mountain etc. In this scenario, I would like to find out for example instances of type person that are very similar, or instances of the type city that are very similar etc. This is the main reason I was interested in knowing how to handle this issue with PBG.

Looking forward to hearing from you and thanking you in advance for your answer

**Comment by lerks** [comment]
From what you say I think you could just split the entities up during post-processing. What I mean is that you train them all as one "universal" entity type, then (after training) you extract the type of each of them and split them up in groups (one group is Swimmer, one is Runner, ...). So then if you want to query for the most similar swimmer, you do the nearest neighbor search only among the entities in the Swimmer group. This should also make your queries more efficient as they work on fewer entities at a time. Would that work?

**Comment by kadimaolivier** [comment]
Thank you very much for your feedback, i really appreciate, let me try all the hopethesis including your suggestions it  might work....and i will definetly come back to you as soon as i have try them.
kind regards

Olivier.K

**Comment by lerks** [comment]
No follow-up for over two weeks, I'm assuming the original poster managed to do what he wanted, I'm closing this. If there are further questions please reopen.
