### ISSUE TITLE
[feature request] Support for loading data from parquet

### ISSUE THREAD

**Issue by gkossakowski** [facebookresearch/PyTorch-BigGraph#114]
This comes from me wanting to try BigGraph on a dataset of moderate size (800mb) but it's a little too large to be exported into tsv files. In particular, I saw that in your converter you iterate over all lines of tsv individually in python which is going to be really slow when over 24 million edges are involved.

Have you considered adding parquet as a supported input file format?

**Comment by lerks** [comment]
PBG's input format is _not_ the TSV format but a mostly HDF5-based format. You can find the code that handles this format in these two files: [graph_storages.py](https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/graph_storages.py) and [checkpoint_storage.py](https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/checkpoint_storage.py). We support the TSV format as a convenient helper to get people started quickly, but all we do with it is convert the input TSV to the HDF5 format and then convert the output back to TSV.

I didn't know Parquet and have never used it. However, if you want to use it, I encourage you to write a importer+exporter for Parquet, along the same lines as the TSV one. If you do so please send your work as a pull request as we'd be happy to merge it upstream.

(An alternative to writing an importer+exporter is to write a new set of storages, however this is quite a bit more complicated and probably not really worth it. Also, the storage interface is quite new and may change in the future, causing you problems).

**Comment by gkossakowski** [comment]
Thanks for the response!

Yeah, I do realize that under the hood you use HDF5 but the underlying storage isn't advertised as an official API (no docs, no mention in the readme). It's not clear to me what would be a minimal implementation of, e.g. importer. 

What would help immensely is a minimal example of an importer. For example, given `['a', 'b', 'c']` nodes and a few edges `[['a', 'b'], ['a', 'c']]` (under just one relation), what how the code would look that invokes all necessary functions in the underlying storage?

Looking at tsv importer, it seems to me that the sequence is not trivial but maybe I'm missing something?

If there was a minimal example, I would give parquet importer a go. Parquet is popular column-oriented data format for big data tools like Hadoop or Spark.

**Comment by lerks** [comment]
In our mind `import_from_tsv` was supposed to be the simplest implementation of an importer, to be used as a template for other importers, like in your case. Apart from the parsing of the TSV files, all it does is pre-process the data and then call the appropriate methods of the EntityStorage, RelationTypeStorage and EdgeStorage. It's these classes that deal with the HDF5 format, so all the importer needs to produce is the internal representation as, say, EdgeLists.

The complexity inside `import_from_tsv` comes from the fact that the pre-processing it must do is not trivial. I described it in more detail in #108, in particular in this comment: https://github.com/facebookresearch/PyTorch-BigGraph/issues/108#issuecomment-542170538. So far each importer needs to re-implement that logic, but in effect it would make sense to extract it to a common function that all the interpreters can call, thus making them simpler. I don't have time now to do this but if you want to take a shot at it go for it!

If you want to do an importer for your specific dataset you might be able to leverage specific properties (e.g., only one relation type, only one partition/bucket, data already partitioned, ...) which will make the importer's job simpler, but then this importer wouldn't be generic and we couldn't merge it upstream.

If you're interested, an overview of the HDF5 format is given [here](https://torchbiggraph.readthedocs.io/en/latest/input_output.html).

**Comment by gkossakowski** [comment]
Yes, I understand that's a demo. Where I'm coming from: I'm working with a large, rather sparse and heavy tailed graph and I'm trying to evaluate whether graph embeddings as implemented by BigGraph make sense as a direction for ml approach to underlying problem I'm trying to solve. Reading your paper, it looks like a good fit but without testing it out, it's hard to say. And testing it out is expensive due to slow importing.

For the time being, I decided to trade my time for computer's time and let the slow importing to just run in background.

In any case, the pointers to #108 are helpful and it's good to know I'm not the first one requesting faster importing. As you said, a highly specialized importer for my particular dataset might be quick to implement and I might just do that to validate whether BigGraph, or graph embeddings in general, are a fruitful direction.

**Comment by adamlerer** [comment]
@gkossakowski sorry I didn't mention this earlier: if you look at `import_from_tsv.py`, it actually just reads lines from the file in a couple places (search for `edgepath.open(` in `import_from_tsv.py`). You should be able to just modify a few lines in those places to support Parquet.

I think we're going to abstract those parts out into a `Reader` object so it's easy to swap out different file types without messing with the whole big `import_from_tsv` file.

**Comment by gkossakowski** [comment]
@adamlerer oh, neat suggestion! I didn't think of it but it makes sense in retrospect!

cc @stephchen

**Comment by lw** [comment]
@adamlerer did this in #120
