### ISSUE TITLE
train.train_and_report_stats(config) is failing with exception ZeroDivisionError

### ISSUE THREAD

**Issue by itarinka** [facebookresearch/PyTorch-BigGraph#115]
## Steps to reproduce

  1.  Run train.train_and_report_stats with small quantity of data on a fast machine

## Observed Results

Script failed with a stack trace:
  File "d:\a\1\s\ETL\train.py", line 16, in train
    for (i, _, stats, _) in tbg_train.train_and_report_stats(config):
  File "C:\hostedtoolcache\windows\Python\3.7.5\x64\lib\site-packages\torchbiggraph\train.py", line 787, in train_and_report_stats
    f"bucket {total_buckets - remaining} / {total_buckets} : "
ZeroDivisionError: float division by zero
##[error]C:\hostedtoolcache\windows\Python\3.7.5\x64\python.exe failed with return code: 1

It looks that io_time or compute_time is zero.

## Expected Results

 Do not divide on zero time

## Relevant Code

train.train_and_report_stats(config)

**Comment by lerks** [comment]
Thanks for reporting this! It is odd that any of these values is exactly zero: even if nothing is really done, the Python interpreter is running thus some time must pass. I'm noticing you're using Windows, which is a platform we never used and support on a best-effort basis. I am worried that the issue may be that on Windows `time.time()` has a lower resolution than on Linux, meaning that subsequent calls that are close one to another may get the same value. I couldn't find a definitive answer about this on the internet though. However, I have been wanting to switch from `time.time` to `time.monotonic` for a while, which is supposed to be more reliable and perhaps at a higher resolution.

To make sure, could you run the following on you Python interpreter? (the outputs are the values I'm getting on my Mac)
```
>>> import time
>>> time.get_clock_info("time").resolution
1e-06
>>> time.get_clock_info("monotonic").resolution
1e-09
```

**Comment by itarinka** [comment]
I see that in the documentation of Python (on https://docs.python.org/3/library/time.html) said:
"Note that even though the time is always returned as a floating point number, not all systems provide time with a better precision than 1 second." 

I tested a resolution on my machine. Unfortunately, the results are
time resolution: 1.562500e-02
monotonic resolution: 1.562500e-02

**Comment by lerks** [comment]
I did some more digging and it seems that `perf_counter` has a high resolution on both Windows and Linux and may be the solution here (see https://www.python.org/dev/peps/pep-0564/#windows).
Could you let me know what `time.get_clock_info("perf_counter").resolution` returns on your machine?

**Comment by lw** [comment]
@adamlerer replaced `time.time()` with `time.perf_counter()` in c7dea47d2e55137bbacd6a1c1a3e4e0c77dcea7f which should have a very high resolution also on Windows and should thus avoid this division by zero. Please reopen if you still encounter the issue.
