### ISSUE TITLE
Clarification Question: What are the restrictions on the number of partitions?

### ISSUE THREAD

**Issue by JSybrandt** [facebookresearch/PyTorch-BigGraph#121]
I am wondering how to interpret the following statement from the documentation:

>For technical reasons, at the current state all entity types that appear on the left-hand side of some relation type must be divided into the same number of partitions (except unpartitioned entities). The same must hold for all entity types that appear on the right-hand side. In numpy-speak, it means that the number of partitions of all entities must be broadcastable to the same value.

Does it mean this:
```
Let P(t) be the number of partitions that divide type t.
Let x->y be a relationship from lhs type x to rhs type y.
If there exist relationships a -> b and c->d, 
  and P(a),P(b),P(c),P(d) > 1, 
  then P(a) == P(c) and P(b) == P(d)
```

**Comment by JSybrandt** [comment]
Follow up, does it follow that if I have a relation `a->a` then `for all entity types x, if P(x) > 1 then P(x) == P(a)`

**Comment by lerks** [comment]
Yes, it means exactly what you said.

If you want one more equivalent formulation:
![image](https://latex.codecogs.com/gif.latex?%5Cexists%20N_%5Ctext%7Blhs%7D%2C%20N_%5Ctext%7Brhs%7D%20%5Ctext%7B%20such%20that%20%7D%20%5Cforall%20x%20%5Crightarrow%20y%20%5Ctext%7B%20we%20have%20%7D%20P%28x%29%20%5Cin%20%5C%7B1%2C%20N_%5Ctext%7Blhs%7D%5C%7D%20%5Ctext%7B%20and%20%7D%20P%28y%29%20%5Cin%20%5C%7B1%2C%20N_%5Ctext%7Brhs%7D%5C%7D)

In the code, such a check is implemented here:
https://github.com/facebookresearch/PyTorch-BigGraph/blob/fc6140865be79771b874e84ecf5736c962ee480c/torchbiggraph/util.py#L260-L290

**Comment by JSybrandt** [comment]
Thank you!
