### ISSUE TITLE
Any restriction when using operator 

### ISSUE THREAD

**Issue by makcedward** [facebookresearch/PyTorch-BigGraph#122]
## Steps to reproduce
Change operator from None to other operators (e.g., `translation`, `linear`) caused an error but it works well if using None operator.

After building a baseline model by using a default value, planning to evaluate other operators to see model performance. However, an exception is thrown when `operator` is not equal to none (e.g. `translation`, `linear`). Would you mind advising any other config needed to be changed? 

## Example of Config
```
relations=[{
            'name': 'rel1',
            'lhs': 'a',
            'rhs': 'b',
            'operator': 'translation',
        }, {
            'name': 'rel2',
            'lhs': 'a',
            'rhs': 'c',
            'operator': 'translation',
        }, {
}]
```

## Exception
```
    203         For IP sockets, the address info is a pair (hostaddr, port).
    204         """
--> 205         fd, addr = self._accept()
    206         # If our type has the SOCK_NONBLOCK flag, we shouldn't pass it onto the
    207         # new socket. We do not currently allow passing SOCK_NONBLOCK to

OSError: [Errno 24] Too many open files
```

**Comment by lerks** [comment]
I've never encountered such an error before, but let me take a stab at it. Each parameter that we use needs to be shared among the worker processes, and we do so using PyTorch's shared memory, which on Linux machines is implemented using [`shm_open`](https://linux.die.net/man/3/shm_open) to obtain a file descriptor and then `mmap` to map its contents to a memory range. Each process however has a limited number of file descriptors it can have open at any given time, and I guess you are hitting the limit. You can check such a limit by running `ulimit -n -S` (for the "soft" limit) or `ulimit -n -H` (for the hard limit) in the same shell where you would run PBG. On my system, for example, I get 65535 for both, and that's typically fine. If you have a lower value you probably will have to raise it. You can easily raise the soft limit to match the hard limit by running `ulimit -n hard`. If that's still not enough you'll have to raise the hard limit too, but the way to do that is system-dependent I think, so I advise you to go check your system's documentation in that case. Let me know if this helps!

**Comment by makcedward** [comment]
Thank you for your suggestion. The exception is still occurred even ulimit is larger than 10 times of 65535. On the other hand, not sure whether it is related or not. I got a similar (subprocess issue) when verbose is larger than 1 (changed to 10 accidentally) although debug message will be printed if verbose is large than 1. 

Will trace the parallel mechanism to find the root cause. FYI, I am using standalone machine to process around 1 GB data. 

Exception when verbose is larger than 1
```
~/.local/lib/python3.6/site-packages/torchbiggraph/train.py in train_and_report_stats(config, model, trainer, evaluator, rank, subprocess_init)
    758                 ])
    759                 all_eval_stats_before = \
--> 760                     get_async_result(future_all_eval_stats_before, pool)
    761                 eval_stats_before = Stats.sum(all_eval_stats_before).average()
    762                 bucket_logger.info(f"Stats before training: {eval_stats_before}")

~/.local/lib/python3.6/site-packages/torchbiggraph/util.py in get_async_result(future_res, pool, health_check_interval)
    242             if not p.is_alive():
    243                 raise RuntimeError(
--> 244                     f"A subprocess exited unexpectedly with status {p.exitcode}")
    245 
    246 

RuntimeError: A subprocess exited unexpectedly with status 1
```

**Comment by lerks** [comment]
The new error doesn't provide much insight: it says one subprocess died with an exception, but doesn't say what exception that was.

As for the original problem, it is still possible that the limit that is in effect for PBG is different than the one you see in the shell, so we could check that, but it would require patching the code. Thus, first, I want to check a different thing: in the error you posted you didn't include a full stack trace, so I cannot see what file contains the code snippet that caused the error. Could you provide a full error and stack trace, and any logs that appear relevant?

**Comment by makcedward** [comment]
I figure out that it can run in python kernel while I use Jupyter Notebook previously. I think it may be some conflict between Jupyter Notebook kernel and subprocess kernel. Prefer to close this issue as it does not relate to PBG. 

FYI, Here is the exception and it repeats numerous times.

```
OSError                                   Traceback (most recent call last)
/usr/lib/python3.6/multiprocessing/resource_sharer.py in _serve(self)
    140         while 1:
    141             try:
--> 142                 with self._listener.accept() as conn:
    143                     msg = conn.recv()
    144                     if msg is None:

/usr/lib/python3.6/multiprocessing/connection.py in accept(self)

/usr/lib/python3.6/multiprocessing/connection.py in accept(self)

/usr/lib/python3.6/socket.py in accept(self)
    203         For IP sockets, the address info is a pair (hostaddr, port).
    204         """
--> 205         fd, addr = self._accept()
    206         # If our type has the SOCK_NONBLOCK flag, we shouldn't pass it onto the
    207         # new socket. We do not currently allow passing SOCK_NONBLOCK to

OSError: [Errno 24] Too many open files
```

**Comment by lerks** [comment]
I'm not sure I understood: are you saying you figured out what causes the issue, and it was due to using Jupyter notebooks? Personally I've never tested on them, so I wouldn't now if they behave differently. The way we intend for PBG to be used is through the command line, so you should try that to see if it's still not working.

**Comment by makcedward** [comment]
The root cause is still the limit of resource allocation. However, I noticed that ulimit -n -S result changed (or not updated to latest change) when using Juptyerbook. But I did not drill down to understand the behavior of that as I use the command line for training indeed.

**Comment by makcedward** [comment]
Finally, I figured out the root cause. 

I updated setting (ulimit -n hard) via native python kernal but not Jupyter notebook's kernel. In other words, "ulimit -n hard" need to be executed in jupyter notebook's kernel.

**Comment by lerks** [comment]
I understand that this issue has been solved, right? If not, feel free to reopen
