### ISSUE TITLE
kernel crashes when training model

### ISSUE THREAD

**Issue by stillmatic** [facebookresearch/PyTorch-BigGraph#126]
## Steps to reproduce

  1. Load and convert input data with 22.7M entities, 62.4M edges in train, 20.8M edges in test. The conversion here executes on a single machine (96 CPU, 614gb RAM) without issue (though, the operations are single-threaded but I assume that is by design?)
2. Attempt to train (`train(train_config, subprocess_init=subprocess_init)`) from Python interactive terminal / Jupyter notebook. (Is it necessary to run as a main file?)

## Observed Results

The kernel immediately crashes.

## Expected Results

It does not crash. I have tried partitioning the user_id entity with `num_partitions = [1, 4, 10]` and the results are exactly the same. Each edge file is roughly 157MB, which is not small, but the memory on the single machine is also pretty big.

## Relevant Code

I have mostly followed the code from https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/examples/livejournal.py while training. The big difference would be that I used a separate, proprietary dataset and included a "relationship" column. For simplicity, let's say the data is a graph of user_id's which have some interaction with each other. 

Do you have any advice here?

**Comment by lerks** [comment]
I can't really say much without seeing more details. What do you mean by "crash"? Is an exception raised? Is there an error message? What is the exit code of the process?

Also, we've seen issues when PBG is run from within Jupyter or similar environments because they seem to impose artificial limits on resources (see #122). Could you launch the training from the command line?

It would also be very helpful if you could post the config and the logs up to the point where it crashed.

**Comment by stillmatic** [comment]
Thanks for the reply! I decided to try running the code as a python executable rather than in an Jupyter environment, and got a traceback (in Jupyter, there is no traceback and the kernel crashes). 

Here is the config:
```
def get_torchbiggraph_config():
    config = dict(
        # I/O data
        entity_path="data/",
        edge_paths=["data/train_partitioned", "data/test_partitioned"],
        checkpoint_path="model/example_1",
        # Graph structure
        entities={"user_id": {"num_partitions": 10},},
        relations=[
            {
                "name": "interaction",
                "lhs": "user_id",
                "rhs": "user_id",
                "operator": "complex_diagonal",
            }
        ],
        # dynamic_relationships=True,
        # Scoring model
        dimension=400,
        global_emb=False,
        comparator="dot",
        # Training
        num_epochs=50,
        num_uniform_negs=1000,
        loss_fn="softmax",
        lr=0.1,
    )
    return config
```

and the `run.py` I am using:
```
import argparse
import random
from itertools import chain
from pathlib import Path

import attr
import pkg_resources

from torchbiggraph.config import add_to_sys_path, ConfigFileLoader
from torchbiggraph.converters.import_from_tsv import convert_input_data
from torchbiggraph.converters.utils import download_url, extract_gzip
from torchbiggraph.eval import do_eval
from torchbiggraph.train import train
from torchbiggraph.util import (
    set_logging_verbosity,
    setup_logging,
    SubprocessInitializer,
)


TRAIN_FILENAME = "train.txt"
TEST_FILENAME = "test.txt"
FILENAMES = [
    TRAIN_FILENAME,
    TEST_FILENAME,
]
TRAIN_FRACTION = 0.75

data_dir = Path('data/')

            
def main() -> None:
    from torchbiggraph.config import parse_config
    import attr
    loader = ConfigFileLoader()
    config = loader.load_config("config_1.py")
    set_logging_verbosity(config.verbose)
    subprocess_init = SubprocessInitializer()
    subprocess_init.register(setup_logging, config.verbose)
    subprocess_init.register(add_to_sys_path, loader.config_dir.name)
    input_edge_paths = [data_dir / name for name in FILENAMES]
    output_train_path, output_test_path = config.edge_paths
    
    train_config = attr.evolve(config, edge_paths=[output_train_path])
    train(train_config, subprocess_init=subprocess_init)

    eval_config = attr.evolve(config, edge_paths=[output_test_path])
    do_eval(eval_config, subprocess_init=subprocess_init)
    
if __name__ == "__main__":
    main()
```

with that, I am able to see the following traceback:
```
  File "./run.py", line 82, in <module>
    main()
  File "./run.py", line 76, in main
    train(train_config, subprocess_init=subprocess_init)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/train.py", line 938, in train
    for _ in train_and_report_stats(config, model, trainer, evaluator, rank, subprocess_init):
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/train.py", line 472, in train_and_report_stats
    checkpoint_manager.register_metadata_provider(ConfigMetadataProvider(config))
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/checkpoint_manager.py", line 193, in __init__
    self.json_config_dict = json.dumps(config.to_dict(), indent=4)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/schema.py", line 331, in to_dict
    return Dumper().map_with_type(self, type(self))
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/schema.py", line 162, in map_with_type
    return self.map_schema(data, type_)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/schema.py", line 243, in map_schema
    result[key] = self.map_with_type(getattr(data, key), field.type)
  File "/usr/local/lib/python3.7/site-packages/torchbiggraph/schema.py", line 163, in map_with_type
    raise NotImplementedError("Unknown type: %s" % type_)
NotImplementedError: Unknown type: typing.Union[float, NoneType]
```

**Comment by jlbar** [comment]
I am receiving this same error just running the `torchbiggraph_example_fb15k` command out of the box.

**Comment by stillmatic** [comment]
I confirmed that my data does not have missing values and I am still getting the same error.

**Comment by huidongchen** [comment]
I am also seeing the same error. It looks like the step `config.to_dict()` in "checkpoint_manager.py" is causing it. 

```
class ConfigMetadataProvider(MetadataProvider):

    def __init__(self, config: ConfigSchema) -> None:
        self.json_config_dict = json.dumps(config.to_dict(), indent=4)

    def get_checkpoint_metadata(self) -> Dict[str, Any]:
        return {"config/json": self.json_config_dict}
```


The error can be simply reproduced by running:

```
loader = ConfigFileLoader()
config = loader.load_config(config_file,overrides)
config.to_dict()
```

**Comment by huidongchen** [comment]
> I am also seeing the same error. It looks like the step `config.to_dict()` in "checkpoint_manager.py" is causing it.
> 
> ```
> class ConfigMetadataProvider(MetadataProvider):
> 
>     def __init__(self, config: ConfigSchema) -> None:
>         self.json_config_dict = json.dumps(config.to_dict(), indent=4)
> 
>     def get_checkpoint_metadata(self) -> Dict[str, Any]:
>         return {"config/json": self.json_config_dict}
> ```
> 
> The error can be simply reproduced by running:
> 
> ```
> loader = ConfigFileLoader()
> config = loader.load_config(config_file,overrides)
> config.to_dict()
> ```

Just a quick follow-up, in my case after removing `import pandas as pd` the issue is solved.

**Comment by lerks** [comment]
Thank you all for looking into this, and sorry we haven't kept you posted. We have a fix for the `Unknown type: typing.Union[float, NoneType]` error in the works and it should be out soon.

**Comment by stillmatic** [comment]
sweet - i can confirm that the latest version on github works when running the `torchbiggraph_example_fb15k` command. going to close - thanks for the fix!

```
2020-03-24 17:50:16,416   [Evaluator] ( 0 , 0 ): Processed 59071 edges in 29 s (0.0021M/sec); load time: 0.028 s
2020-03-24 17:50:16,417   [Evaluator] Stats for edge path 1 / 1, bucket ( 0 , 0 ): pos_rank:  91.8395 , mrr:  0.764777 , r1:  0.708884 , r10:  0.859102 , r50:  0.913189 , auc:  0.98754 , count:  59071
2020-03-24 17:50:16,417   [Evaluator] 
2020-03-24 17:50:16,417   [Evaluator] Stats for edge path 1 / 1: pos_rank:  91.8395 , mrr:  0.764777 , r1:  0.708884 , r10:  0.859102 , r50:  0.913189 , auc:  0.98754 , count:  59071
2020-03-24 17:50:16,417   [Evaluator] 
2020-03-24 17:50:16,417   [Evaluator] 
2020-03-24 17:50:16,417   [Evaluator] Stats: pos_rank:  91.8395 , mrr:  0.764777 , r1:  0.708884 , r10:  0.859102 , r50:  0.913189 , auc:  0.98754 , count:  59071
```
