### ISSUE TITLE
Interpretation of Complex output

### ISSUE THREAD

**Issue by izuna385** [facebookresearch/PyTorch-BigGraph#133]
https://torchbiggraph.readthedocs.io/en/latest/related.html#complex
Based on Complex embedding, my question is related to output tsv file of complex embedding.
My interpretation is that, when dimension is set to 300, 1-150th's numbers are real and 151-300 are imaginary. Is this correct?

Why I asked this is because, I'd like to conduct ANN search with output tsv of complex embeddings.
If you'd know about this, I'd appreciate it. Thanks.

**Comment by timlacroix** [comment]
Yup I believe that's right.
To see how these embeddings can be used to compute a score for a triple with an operator you can have a look at ComplexDiagonalOperator.forward

**Comment by izuna385** [comment]
Thanks for reply. I'll check it.
