### ISSUE TITLE
How to integrate pytorch-biggraph with horovod runner?

### ISSUE THREAD

**Issue by kishensurajp** [facebookresearch/PyTorch-BigGraph#136]
Hi, I want to know if it is possible to integrate this library with Horovod runner? https://github.com/horovod/horovod

**Comment by lw** [comment]
I'm not familiar with Horovod but from quickly googling it looks like it does a superset of the functions done by `torch.distributed`, adding support for scheduling and a few more things. I don't think we're interested in ripping out the torch.distributed usage, adding an additional dependency and buying into that framework. I think torch.distributed is a good sweet spot in terms of level of abstraction.

**Comment by kishensurajp** [comment]
@lw , thanks for the remarks!
