### ISSUE TITLE
Pre-trained embeddings for DBPedia

### ISSUE THREAD

**Issue by MaxPflueger** [facebookresearch/PyTorch-BigGraph#138]
Hi,

Is there a plan to release pre-trained embeddings for other datasets (e.g. DBPedia)? 

Thanks in advance!

**Comment by adamlerer** [comment]
I don't think so, but if you're interested in training and contributing DBPedia embeddings, we'd love to host them!

cc @ledw who trained the FreeBase embeddings, in case she has or plans to train DBPedia embeddings.

**Comment by ledw** [comment]
We currently do not have plans to train DBPedia embeddings. @MaxPflueger If you're interested in training it we'd be happy to help.

**Comment by MaxPflueger** [comment]
Thanks for your responses. I decided to use a small subset of DBPedia for initial experiments. My schedule is quite busy at the moment but I would be happy to contribute at some point. @ledw I will get back to your offer if I can free up some time.
