### ISSUE TITLE
Link to a paper in the Readme file doesn't work

### ISSUE THREAD

**Issue by ksbsk** [facebookresearch/PyTorch-BigGraph#139]
## Steps to reproduce

  1. Reading `Getting started` section of the README file
  2. Clicking on the link to the paper (https://www.sysml.cc/doc/2019/71.pdf) referenced there

## Observed Results

The following error occurs:
`Document does not exist. This has been reported to an engineer.`

**Comment by lw** [comment]
What version of the README are you looking at? We've fixed this issue on the master branch some time ago, because the conference where we published changed name and website, but we cannot update old versions of the README.

**Comment by ksbsk** [comment]
I'm looking at the most recent version of the README at https://github.com/facebookresearch/PyTorch-BigGraph

From what I see in the latest commit for this file, it is clear that the change of the paper URL was only applied in one place:
https://github.com/facebookresearch/PyTorch-BigGraph/commit/c649cf3b70d083d74d253cc95f509eb74fd64fce

Whereas it should have been fixed also for lines no. 45 and 119

**Comment by lw** [comment]
Oh, you're right, thanks for spotting and reporting that! I've fixed it in bad0017d5bbdd2a1bf3a4e363b4d430aa16491b2.
