### ISSUE TITLE
Does PBG edge support weight now?

### ISSUE THREAD

**Issue by pinkney03** [facebookresearch/PyTorch-BigGraph#140]
I checked the previous issues, on July 2019, it seems your were working on that then. Any update? Thanks

**Comment by AlekseiPol** [comment]
Seems commit https://github.com/facebookresearch/PyTorch-BigGraph/commit/b590de4c61fe7185827e44ad41ef21ddcd8239a8 implements it.  
But so far I have not found feature description anywhere.

**Comment by rkindi** [comment]
At the moment, PBG supports edge weights for CPU training but not for GPU training

https://github.com/facebookresearch/PyTorch-BigGraph/blob/67c42f9002ad7d0f03d532ea8cc165818e48bafc/torchbiggraph/train_gpu.py#L498

To use the feature, you just need to add an additional column to your edgelist data with the weight.
