### ISSUE TITLE
Wikidata Embeddings have the description as the key instead of the QID

### ISSUE THREAD

**Issue by kireet** [facebookresearch/PyTorch-BigGraph#15]
I downloaded the pretrained wikidata embeddings, and i see lines like:
```
"scientific article published on January 1986"@en-gb	-0.3222	-0.6460	-0.1054	0.2531 ...
```

This seems to be the description of the wikidata entity. I think the QID, e.g. `Q2` for earth, should be used as the unique identifier as even the entity title is not necessarily unique.

**Comment by kireet** [comment]
also how about compressing the file for quicker downloads?

**Comment by loretoparisi** [comment]
@kireet so in the Wikidata embeddings a row has no class identifier (I mean the SPARQL class Q ids and properties ids)?

**Comment by kireet** [comment]
I scanned the first thousand or so and it just seems like description and then the embedding

**Comment by lerks** [comment]
@ledw is probably the best person to answer this, assigning to her.

**Comment by ledw** [comment]
@kireet @loretoparisi Hi, thanks for the question. The wikidata embeddings should include *both* class identifier (starting with Q ids, in a form of a full link) and the description as @kireet mentioned. The reason that description is included is because that it appears as the target in the RDF format we used to train. We could take them out, or sort the embeddings according to identifier v.s. description.

**Comment by kireet** [comment]
yep, you are right! sorry about that. just so i understand, each entity is in the file twice, one with it's description and one with it's QID?

**Comment by lerks** [comment]
> also how about compressing the file for quicker downloads?

In #26 I'm adding a link to the gzipped embeddings.

**Comment by lerks** [comment]
Btw, a machine readable version of the data is available here:
- [wikidata_translation_v1_names.json.gz](https://dl.fbaipublicfiles.com/torchbiggraph/wikidata_translation_v1_names.json.gz) (378MiB), a gzipped JSON-encoded list of all the keys in the first column of the TSV file;
- [wikidata_translation_v1_vectors.npy.gz](https://dl.fbaipublicfiles.com/torchbiggraph/wikidata_translation_v1_vectors.npy.gz) (39.9GiB), a gzipped serialized numpy array with the 200-dimension vectors, one for each line of the TSV file.

**Comment by nandana** [comment]
Thanks a lot for the pretrained Wikidata embeddings. Those are really helpful.

@ledw I have a similar to a question as @kireet about the two files, trying to understand their content:
- wikidata_translation_v1_names.json.gz 
- wikidata_translation_v1_vectors.npy.gz 

Each of them has 78,413,185 lines and looking at the number of entities in Wikidata around `2019-03-06` I assume some of the entities are repeated in the files, right? One entry as the `QID` with prefex `http://www.wikidata.org/entity/` and the other as the description. 

I just filtered out the ones only with QID, and they are 55,032,667.  So if I use only them, I am not losing anything, right?
