### ISSUE TITLE
Examples for distributed training

### ISSUE THREAD

**Issue by Bin-Go2** [facebookresearch/PyTorch-BigGraph#161]
Hi, I looked through the example codes and didn't find the distributed version for training. And after reviewing the documentation I did some codes, but cannot make it. If possible, could you please share a distributed example for graph embedding? 
 
Thanks.

**Comment by lw** [comment]
It's hard to provide a self-contained example for distributed training as it needs to set-up a network file-system, a rendezvous path, and launch on multiple machines.

If you let us know what parts of the docs were unclear we can explain better (and fix the docs for future users).

**Comment by Bin-Go2** [comment]
Sure. Here is my what I encounter when I try to implement distributed PBG:

```
Looking up relation types in the edge files...
- Found 23 relation types
- Removing the ones with fewer than 1 occurrences...
- Left with 23 relation types
- Shuffling them...
Searching for the entities in the edge files...
Entity type all:
- Found 15652 entities
- Removing the ones with fewer than 1 occurrences...
- Left with 15652 entities
- Shuffling them...
Preparing counts and dictionaries for entities and relation types:
- Writing count of entity type all and partition 0
- Writing count of entity type all and partition 1
- Writing count of dynamic relations
Preparing edge path output/1/edges_partitioned, out of the edges found in tmp/framenet.tsv
- Edges will be partitioned in 2 x 2 buckets.
- Processed 54109 edges in total
2020-10-21 09:26:58,766   [Trainer-0] Loading entity counts...
2020-10-21 09:26:58,859   [Trainer-0] Setup lock server...
2020-10-21 09:26:58,869   [Trainer-0] Setup param server...
2020-10-21 09:26:58,882   [Trainer-0] init_process_group start
```
It seems that I cannot successfully init the process group, So could you please tell me what the correct steps that I need to do?  

PS: What I did:
1. set the raw_config dictionary by adding  num_machines = 2,  distributed_init_method='tcp://my loptop's ip:23456'
2. 
```
 setup_logging()
    config = parse_config(raw_config)
    subprocess_init = SubprocessInitializer()
    input_edge_paths = [tmp_tsv_path] 

    convert_input_data(
        config.entities,
        config.relations,
        config.entity_path,
        config.edge_paths,
        input_edge_paths,
        TSVEdgelistReader(lhs_col=0, rel_col=1, rhs_col=2),
        dynamic_relations=config.dynamic_relations,
    )
    train(config, subprocess_init=subprocess_init)
```

**Comment by lw** [comment]
What are the logs of the second trainer?

**Comment by Bin-Go2** [comment]
actually, for the second machine, the log is the same
```
Looking up relation types in the edge files...
- Found 23 relation types
- Removing the ones with fewer than 1 occurrences...
- Left with 23 relation types
- Shuffling them...
Searching for the entities in the edge files...
Entity type all:
- Found 15652 entities
- Removing the ones with fewer than 1 occurrences...
- Left with 15652 entities
- Shuffling them...
Preparing counts and dictionaries for entities and relation types:
- Writing count of entity type all and partition 0
- Writing count of entity type all and partition 1
- Writing count of dynamic relations
Preparing edge path output/1/edges_partitioned, out of the edges found in tmp/framenet.tsv
- Edges will be partitioned in 2 x 2 buckets.
- Processed 54109 edges in total
2020-10-21 09:26:58,766   [Trainer-0] Loading entity counts...
2020-10-21 09:26:58,859   [Trainer-0] Setup lock server...
2020-10-21 09:26:58,869   [Trainer-0] Setup param server...
2020-10-21 09:26:58,882   [Trainer-0] init_process_group start
```
So I think may I didn't successfully initialize the distributed communication.
By the way, when I implement the command line torchbiggraph_train --rank 0 embeddings/config_dist.py 
It comes up the error AttributeError: module 'torchbiggraph_config_31829f74c8c14becb92439c747480c09' has no attribute 'get_torchbiggraph_config'
I am wondering what the config.py referred on the documentation is. In my opinion, the config.py returns a config dictionary that we set, right?

**Comment by lw** [comment]
If that's the log the second machine then there's something odd going on, because both processes think they are "Trainer-0", whereas one of them should be "Trainer-1". Are you sure you're passing `--rank=1` to the second process?

**Comment by lw** [comment]
As for that AttributeError, could you give me the full exception log, including the traceback? And the verbatim copy of the config file you're passing. Thanks

**Comment by Bin-Go2** [comment]
```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/CSKG/bin/torchbiggraph_train", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/CSKG/lib/python3.6/site-packages/torchbiggraph/train.py", line 961, in main
    config = loader.load_config(opt.config, overrides)
  File "/opt/anaconda3/envs/CSKG/lib/python3.6/site-packages/torchbiggraph/config.py", line 471, in load_config
    config_dict = self.load_raw_config(path)
  File "/opt/anaconda3/envs/CSKG/lib/python3.6/site-packages/torchbiggraph/config.py", line 463, in load_raw_config
    raw_config = module.get_torchbiggraph_config()
AttributeError: module 'torchbiggraph_config_988ec6d6cd5b491baf09dc2cf62c7722' has no attribute 'get_torchbiggraph_config'
```
And for your "Trainer-1" problem, to be honest, that's what my confusion is. I don't have the chance to set the rank . Since I only set the num_machines and distributed_init_method in the config dictionary and my plan is to initialize the  progress group on my both two machines and then try to use the command line 
`torchbiggraph_train --rank 1 embeddings/config_dist.py` for the 1st machine,
`torchbiggraph_train --rank 2 embeddings/config_dist.py` for the 2nd machine,

**Comment by Bin-Go2** [comment]
LOL, I try to use the code running on one machine to imitate a distributed version (tcp://127.0.0.1:23456)  and it works. 😂 So the problem is the structure of my distribute nodes and nothing wrong with PBG I will deal with it. 
Anyway, I really appreciate your help!

**Comment by lw** [comment]
The rank is not part of the config because it's different on each trainer (whereas the config should be exactly the same for all trainers). Also, ranks are 0-based, so if you have two trainers their ranks are `0` and `1`, and not `1` and `2`.

Anyways, I'm glad you managed to solve your problem!
