### ISSUE TITLE
CPU usage limitation

### ISSUE THREAD

**Issue by Bin-Go2** [facebookresearch/PyTorch-BigGraph#164]
Hi, when I do graph embedding and use htop to check the CPU usage. I find that PBG occupies all CPUs by default like Pytorch. When I try to set the `torch.set_num_threads(3) ` in my main function. It doesn't work. I am wondering if there are some ways to help limit the CPU usage.

**Comment by lw** [comment]
You should probably take a look at the `workers` config param (see [here](https://torchbiggraph.readthedocs.io/en/latest/configuration_file.html#training))`. It controls how many subprocesses will be spawned by PBG, and each subprocess will try to use a full CPU. By default we'll spawn as many processes as there are CPUs available.

**Comment by Bin-Go2** [comment]
Ops, sorry, I miss the point. Thanks, it works.
