### ISSUE TITLE
pip install torchbiggraph issue

### ISSUE THREAD

**Issue by Bin-Go2** [facebookresearch/PyTorch-BigGraph#168]
Hi, today when I try to use a new virtual environment to use Pytorchbiggrpah. 
After `pip install torchbiggraph` and I go to the site-packages, only finding there is a missing file `torchbiggraph/converters/mporters.py` which should be there.  My converter folder is like:

![image](https://user-images.githubusercontent.com/45792483/98745612-c2667e80-2368-11eb-8afb-63e050200296.png)

**Comment by lw** [comment]
pip installs the stable version found on PyPI, which is v1.0.0. And in that version there wasn't an importers.py file: it has been added later. See here: https://github.com/facebookresearch/PyTorch-BigGraph/tree/v1.0.0/torchbiggraph/converters.

If you need the master version the only way to get it is by cloning the GitHub repo.

**Comment by Bin-Go2** [comment]
Thanks for your reply, but my problem is when I use the stable one, I will get some issues like 
```
`ImportError: cannot import name 'UNPARTITIONED’`
`no module named …`
```

**Comment by lw** [comment]
Could you provide the full error log, and possibly more details about your setup?

My first guess about what could be going on is that you might have both the stable version installed in your environment and the master version available, perhaps, in the working directory, and the two are getting mixed up. If you're trying to use the stable version could you make sure you're removing all copied of the GitHub repo?

**Comment by Bin-Go2** [comment]
I got the exception!
Hi, the exception is like
```
from torchbiggraph.converters.importers import TSVEdgelistReader, convert_input_data
ModuleNotFoundError: No module named 'torchbiggraph.converters.importers'
```
Cause I use this module before, so when I change to the stable version, it missed. 
By the way, could you please help me to use substitute solution to solve it?

**Comment by Bin-Go2** [comment]
Cause  I want to use 
![image](https://user-images.githubusercontent.com/45792483/98932661-79134d80-2494-11eb-9aa7-7a27c0efc274.png)

**Comment by Bin-Go2** [comment]
Never mind, I tried to rebuild my project and include some scripts, now it's fine. Thank you ~
