### ISSUE TITLE
import error in examples 

### ISSUE THREAD

**Issue by sademakn** [facebookresearch/PyTorch-BigGraph#172]
I am trying to run https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/examples/fb15k.py
and in the bellow line It's throwing an error:

`from torchbiggraph.converters.importers import TSVEdgelistReader, convert_input_data`

`ModuleNotFoundError: No module named 'torchbiggraph.converters.importers'`

**Comment by lw** [comment]
What version of PBG do you have installed? Where did you get it from?

My guess is that you're using the 1.0 version (e.g., from PyPI) but you're trying to run code from master, which has since changed a bit and has added a few classes.

**Comment by rkindi** [comment]
Closing. As @lw suggested, please try installing from source using the instructions in the README to resolve your issue.
