### ISSUE TITLE
When using dynamic_rels, how to score the edge (u, r, v)?

### ISSUE THREAD

**Issue by BronzePot** [facebookresearch/PyTorch-BigGraph#183]
When using dynamic_rels, a edge (u, r, v)  is scored c(g_r(u), v) or as c(u, h_r(v)). g_r is the right operator,and h_r is the left operator.
However,when I using the embeddings, which scores should I use, c(g_r(u), v) or c(u, h_r(v))? c(g_r(u), v)+c(u, h_r(v))?

**Comment by lw** [comment]
This is up to you and your application. It may take some experimentation.

Note that the score c(g_r(u), v) is used when comparing (u, r, v) with (u, r, w), hence when the "variable" is v (and u and r are kept constant). And vice versa for c(u, g_r(v)). Hence, depending on how you compare the embeddings, one might make more sense than the other.

**Comment by BronzePot** [comment]
Thanks a lot!

**Comment by rkindi** [comment]
Closing issue
