### ISSUE TITLE
How many negative edges are used to get the rank of a positive edge?

### ISSUE THREAD

**Issue by afung-sharethis** [facebookresearch/PyTorch-BigGraph#185]
https://torchbiggraph.readthedocs.io/en/latest/evaluation.html

```The rank of a positive edge is determined by the rank of its score against the scores of a certain number of negative edges. ```

When it says a "certain" number of negative edges above, what is that number?

**Comment by lw** [comment]
It depends on your config.

If you click on that link it leads you here: https://torchbiggraph.readthedocs.io/en/latest/loss_optimization.html#negative-sampling

Where we explain how negative sampling works, which modes there are, and how many negatives are sampled in each of them. Let me know if anything there isn't clear.

**Comment by afung-sharethis** [comment]
Thanks Luca. Makes sense. The number is determined by the sampling method, which can be all, same-batch, or uniformly-sampled.

**Comment by rkindi** [comment]
Resolved
