### ISSUE TITLE
fb15k.py hang on Mac

### ISSUE THREAD

**Issue by stantonxu** [facebookresearch/PyTorch-BigGraph#19]
## Steps to reproduce

  1. pip install biggraph
  2. git clone the repo
  3. run fb15k.py by "python examples/fb15k.py"

## Observed Results

  * What happened?  This could be a description, log output, etc.

It hangs on Mac,

_2019-04-04 13:58:22  Loading entity counts...
2019-04-04 13:58:22  Creating workers...
2019-04-04 13:58:22  Initializing global model...
2019-04-04 13:58:22  Starting epoch 1 / 50 edge path 1 / 1 edge chunk 1 / 1
2019-04-04 13:58:22  edge_path= data/FB15k/freebase_mtr100_mte100-train_partitioned
still in queue: 0
2019-04-04 13:58:22  Swapping partitioned embeddings None ( 0 , 0 )
2019-04-04 13:58:22  Loading entities
7.67MB [00:29, 397kB/s]_

## Expected Results

  * What did you expect to happen?

Expect to run through

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

Python 3.7.1
macOS High Sierra Version 10.13.6

**Comment by lerks** [comment]
I just ran it on my MacBook Pro and it worked fine (I have Mojave 10.14.4 and Python 3.7.0, but this difference shouldn't matter). So to help you out I need more info.

First of all, are you sure it's hanging and not just computing for a long time without displaying any output? The training process uses only the CPU and, depending on how powerful your machine is and what other programs you have running, it may take a while. You can check by opening the activity monitor and seeing whether the CPU is being used at 100%.

Then, you can modify the `examples/configs/fb15k_config.py` file and add a `verbose=1` option to it. This will print more output and may help understanding where it's getting stuck.

Also, it would be great if you could get some information about the stack while it's hanging. One option would be to kill the program, with Ctrl+C, which should raise an exception and print the stacktrace (may not work if it's hanging deep in some PyTorch code). Even better would be if you could run this with a debugger and follow the chain of calls until it hangs.

Once we have more info we may be able to figure out what's going on.

**Comment by stantonxu** [comment]
@lerks Thank you Luca for your quick response. I gave it a second try, and it worked through. So I think it was not hanging, but just slowly processing. I am going to close this ticket. 

If I encounter any other problem, I will reach out.
