### ISSUE TITLE
how to train embeddings when the same pair of entities have multiple relations?

### ISSUE THREAD

**Issue by circlegao** [facebookresearch/PyTorch-BigGraph#196]
For example:
I have four entities: A,B,C,D
three relation types：r1,r2,r3
data format:
A r1 B
A r2 B
B r3 C
C r2 D
we can see that entity A,B have two relation types:r1 and r2
how should I write configs? Is the following format right?
"entities": {
    "A": {"num_partitions": 1},
    "B": {"num_partitions": 1},
    "C": {"num_partitions": 1},
    "D": {"num_partitions": 1},
},
"relations": [
    {"name": "r1", "lhs": "A", "rhs": "B"},
    {"name": "r2", "lhs": "A", "rhs": "B"},
    {"name": "r2", "lhs": "C", "rhs": "D"},
    {"name": "r3", "lhs": "B", "rhs": "C"}
]

Looking forward to your reply.

**Comment by lw** [comment]
Yes that config should work in my opinion. Are you hitting any issues?

**Comment by rkindi** [comment]
As @lw mentioned, this should work. Closing for now. Feel free to re-open if needed.
