### ISSUE TITLE
TypeError: create_group() got an unexpected keyword argument 'track_order'

### ISSUE THREAD

**Issue by Bishnukuet** [facebookresearch/PyTorch-BigGraph#20]
## Observed Results
Traceback (most recent call last):
.....
...
...

    g = hf.create_group(MODEL_STATE_DICT_GROUP, track_order=True)
TypeError: create_group() got an unexpected keyword argument 'track_order'

**Comment by lerks** [comment]
Apparently the `track_order` argument was [added in version 2.8](https://github.com/h5py/h5py/commit/092ad25a2dea3a2cd154d2248b9327f7f826f15a) of the h5py library. I guess you have an earlier version, is that correct? If so, the easy fix is just to upgrade h5py. Version 2.8 is the one we've mostly tested with, so it definitely works.

To be honest, we could probably do without the `track_order` argument and try to depend on an older version, but there may very well be other 2.8+-only features we're using that I'm not aware of. Also, we require at least version 1.0 of PyTorch, which is more recent than h5py-2.8, thus I don't think it's an unreasonably recent requirement.

However, this issue made me realize that we haven't specified this version constraint in the `requirements.txt` file. If we had then `pip` would have upgraded the version for you, or at least it would have warned you about the issue. I'll send out a pull request to fix this.

**Comment by Bishnukuet** [comment]
Hi Luca, 
Thanks a lot for the quick answer. 
You are absolutely right. I am using a older version of h5py.  I have upgraded the version to 2.9.0 and it is now running without that error. 

Cheers
-Bishnu.
