### ISSUE TITLE
how read and train data from multi files?

### ISSUE THREAD

**Issue by circlegao** [facebookresearch/PyTorch-BigGraph#200]
If I split the train dataset into two files： train1.txt and train2.txt, then how should I change the following command? The following format is wrong:
prepare data:
torchbiggraph_import_from_tsv \
  --lhs-col=0 --rel-col=1 --rhs-col=2 \
  torchbiggraph/examples/configs/fb15k_config_cpu.py \
  [data/ train1.txt,data/train2.txt]

**Comment by lw** [comment]
I think something along those lines should work, why are you saying it's wrong?

**Comment by circlegao** [comment]
It tells me:
FileNotFoundError: [Errno 2] No such file or directory: '[data/ train1.txt,data/train2.txt]'

**Comment by circlegao** [comment]
I want to read data from multi files once.

My data format is parquet, for example: I have 100 data files:
train1.parquet,
train2.parquet,
train3.parquet.
.................................
train100.parquet 
and there stored in the file named data, then 
how show I change the Class ParquetEdgelistReader(EdgelistReader) in importer.py to read these data:
prepare data command:
torchbiggraph_import_from_tsv --lhs-col=0 --rel-col=1 --rhs-col=2  config.py  [data/ *]
It tells me:
FileNotFoundError: [Errno 2] No such file or directory: '[data/ *]'

**Comment by lw** [comment]
I think the problem might be with the syntax of your command: why are you putting brackets around the path? why are you putting a space before the asterisk? why are you separating elements with commas?

Try just doing `torchbiggraph_import_from_tsv ... data/train1.txt data/train2.txt`

**Comment by circlegao** [comment]
ok ,thanks

**Comment by rkindi** [comment]
Seems the issue was resolved by lw's suggestion
