### ISSUE TITLE
what is violators_lhs/violators_rhs？

### ISSUE THREAD

**Issue by illcat** [facebookresearch/PyTorch-BigGraph#201]
Their average is 5 and model converges very slowly on my data set.

This is my config.
```
        # Scoring model
        dimension=200,
        global_emb=False,
        # Training
        num_batch_negs = 500,
        num_uniform_negs = 500,
        num_epochs=30,
        workers=8,
        lr=0.01,
```

**Comment by lw** [comment]
Within a set of negative samples, it's the number of negative edges that "score higher" than the positive edge they correspond to. Ideally it should be zero, although I don't think we prune "duplicates" so in fact one of those negative edges may be a negative and it may in fact be expected/desirable that is scores highly.

It's computed here:
https://github.com/facebookresearch/PyTorch-BigGraph/blob/e63485a7216703cb545ea37d8ceb646b79306edb/torchbiggraph/train_cpu.py#L97-L98

**Comment by illcat** [comment]
> Within a set of negative samples, it's the number of negative edges that "score higher" than the positive edge they correspond to. Ideally it should be zero, although I don't think we prune "duplicates" so in fact one of those negative edges may be a negative and it may in fact be expected/desirable that is scores highly.
> 
> It's computed here:
> https://github.com/facebookresearch/PyTorch-BigGraph/blob/e63485a7216703cb545ea37d8ceb646b79306edb/torchbiggraph/train_cpu.py#L97-L98

Thanks for your reply, I think I already know.
