### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by NielsRogge** [facebookresearch/PyTorch-BigGraph#203]
In the following image, is it possible that it should be "purple relation type" and "green relation type" instead of entity types?

![image](https://user-images.githubusercontent.com/48327001/116679871-51189780-a9ab-11eb-857c-bd64fbddff26.png)

**Comment by lw** [comment]
Yes, correct, thanks for spotting it! Would you mind sending a PR to fix it? Thanks!
