### ISSUE TITLE
Jupyter notebook for format explanation and results visualization 

### ISSUE THREAD

**Issue by YubinXie** [facebookresearch/PyTorch-BigGraph#21]
Thank you for your works!
Will you provide a notebook that display the format request for each step, (ideally including training), and results visualization? Thanks!

**Comment by lerks** [comment]
We hadn't thought about preparing a notebook tutorial. One reason is that we imagine that the typical usage of PBG is as a command-line tool. In that scenario, the README already provides an essential introduction: do you feel anything can be improved there? It is however also possible to use PBG as a library (albeit one with just a couple of narrow entry points). An example of how to do that is the [`examples/fb15k.py`](https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/examples/fb15k.py) file, which translates more or less the steps outlined in the README to calls of PBG's functions.

Do you have anything in mind that isn't already covered by the above materials and that could be presented well as a notebook?

Note also that PBG is intended for batch, not interactive, use. Also, there are no visualization features (yet?), although some discussion about how to inspect and query the output embeddings can be found in #13. If you're interested in projecting the embeddings to a 2- or 3-dimensional space for visualization you could consider the t-SNE technique, it's the one we used in the [blog post](https://ai.facebook.com/blog/open-sourcing-pytorch-biggraph-for-faster-embeddings-of-extremely-large-graphs/) to visualize the Wikidata embeddings.

**Comment by YubinXie** [comment]
Thank you for your reply. I was just hoping to have a simple representation of the whole model from input to output, and play with the output in a interactive way. But no worries. If I did the training on my domain, I will provide a notebook. Thanks!
