### ISSUE TITLE
PBG gails to load data for training--Unable to open backup file on first run

### ISSUE THREAD

**Issue by Jeffrey-Sardina** [facebookresearch/PyTorch-BigGraph#210]
## Issue Summary
Upon running PBG, as spoon as training begins, the program exists with an error saying that there is no checkpoint to load data from. However, since this is the first time I am running training on this data set, no checkpoint have been made yet.

## Issue Summary
Upon running PBG, as spoon as training begins, the program exists with an error saying that there is no checkpoint to load data from. However, since this is the first time I am running training on this data set, no checkpoint have been made yet.
Thank you in advance for the help!

## Steps to reproduce
1. Prepare data on custom dataset (see Relevant Code below) using PBG's native data preparation utility; this part works without error
2. Start the training on the prepared data (See Relevant Code beelow)
3. Training fails after around 5 seconds.

## Observed Results
Training failed, saying it could not load from a checkpoint.;

Error in Terminal:
```
2021-05-17 11:09:17,852   [Trainer-0] Loading entity counts...
2021-05-17 11:09:17,853   [Trainer-0] Creating workers...
2021-05-17 11:09:17,949   [Trainer-0] Initializing global model...
2021-05-17 11:09:17,990   [Trainer-0] Creating GPU workers...
2021-05-17 11:09:17,999   [Trainer-0] Starting epoch 1 / 50, edge path 1 / 1, edge chunk 1 / 1
2021-05-17 11:09:18,003   [Trainer-0] Edge path: ../copies/goa/pbg_split/imported/training_data
2021-05-17 11:09:18,004   [Trainer-0] still in queue: 8
2021-05-17 11:09:18,004   [Trainer-0] Swapping partitioned embeddings None ( 2 , 2 )
2021-05-17 11:09:18,004   [Trainer-0] Loading partitioned embeddings from checkpoint
Process GPU #0:
Traceback (most recent call last):
  File "/home/.../miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/train_gpu.py", line 160, in run
    torch.cuda.check_error(res)
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torch/cuda/__init__.py", line 205, in check_error
    raise CudaError(res)
torch.cuda.CudaError: invalid argument (1)
/home/.../miniconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
./pbg_pipeline.sh: líne 60: 31580 Bus error               (memory dumped) torchbiggraph_train $CONFIG -p edge_paths=../copies/$DATA/pbg_split/imported/training_data
backup_points/goa
2021-05-17 11:09:25,460   [Evaluator] Starting edge path 1 / 1 (../copies/goa/pbg_split/imported/validation_data)
Traceback (most recent call last):
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/checkpoint_storage.py", line 341, in load_entity_partition
    with h5py.File(path, "r") as hf:
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/h5py/_hl/files.py", line 442, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/h5py/_hl/files.py", line 195, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/media/.../backup_points/goa/embeddings_all_0.v0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/.../pytorch-biggraph-gpu/bin/torchbiggraph_eval", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_eval')()
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 262, in main
    do_eval(config, subprocess_init=subprocess_init)
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 239, in do_eval
    for _ in do_eval_and_report_stats(config, model, evaluator, subprocess_init):
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 163, in do_eval_and_report_stats
    embs = load_embeddings(entity, part)
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 114, in load_embeddings
    embs, _ = checkpoint_manager.read(entity, part)
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/checkpoint_manager.py", line 297, in read
    embs, serialized_optim_state = self.storage.load_entity_partition(
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/checkpoint_storage.py", line 350, in load_entity_partition
    raise CouldNotLoadData() from err
torchbiggraph.util.CouldNotLoadData
```

## Expected Results
I expected training to proceed as normal, without failing on the first run.

### To Prepare the Data
$DATA is the name of the dataset in my fiulesystem
$CONFIG is the path to the config fuile in my file system
```
torchbiggraph_import_from_tsv \
        --lhs-col=0 --rel-col=1 --rhs-col=2 \
        $CONFIG \
        ../copies/$DATA/pbg_split/training_data.tsv \
        ../copies/$DATA/pbg_split/validation_data.tsv \
        ../copies/$DATA/pbg_split/testing_data.tsv
```

### To Run Training
$DATA is the name of the dataset in my fiulesystem
$CONFIG is the path to the config fuile in my file system

```
torchbiggraph_train \
        $CONFIG \
        -p edge_paths=../copies/$DATA/pbg_split/imported/training_data
```

### My Config File
```
#!/usr/bin/env python3

def load_params():
    import os

    params = {}
    for key, val in os.environ.items():
        if key == "NUM_PARTITIONS":
            params[key] = int(val)
        if key == "DATA":
            params[key] = val
    
    return params

def get_torchbiggraph_config():
    params = load_params()

    print("backup_points/" + params['DATA'])

    config = dict(
        # I/O data
        entity_path= "../copies/" + params['DATA'] + "/pbg_split",
        edge_paths=[
            "../copies/" + params['DATA'] + "/pbg_split/imported/training_data",
            "../copies/" + params['DATA'] + "/pbg_split/imported/testing_data",
            "../copies/" + params['DATA'] + "/pbg_split/imported/validation_data",
        ],
        checkpoint_path="backup_points/" + params['DATA'],

        # Graph structure
        # Ba cheart go mbeadh méid_graif_eolais / num_partitions < 8GB (cuimhne CUDA)
        entities={"all": {"num_partitions": params["NUM_PARTITIONS"]}},
        relations=[
            {
                "name": "all_edges",
                "lhs": "all",
                "rhs": "all",
                "operator": "complex_diagonal",
            }
        ],
        dynamic_relations=True,

        # Scoring model
        dimension=400,
        global_emb=False,
        comparator="dot",

        # Training
        num_epochs=50,
        batch_size=5000,
        num_uniform_negs=1000,
        loss_fn="softmax",
        lr=0.1,
        regularization_coef=1e-3,

        # Evaluation during training
        eval_fraction=0,

        # GPU
        num_gpus=1,
    )

    return config
```

## Expected Results
I expected training to proceed as normal, without failing on the first run.

**Comment by lw** [comment]
In the middle of the log I'm seeing "Bus error". This is typically a sign that the training ran out-of-memory. (It's normal for this to happen when loading a checkpoint/initializing data, as that's when we allocate the most memory). PBG uses shared memory, which sometimes is "more restricted" than standard memory, hence PBG could OOM even if it appears there's still memory on the system. The most common scenario where shared memory is constrained is when running under Docker (or other containers). This is unsupported and we recommend running on bare metal. If however you have to use Docker, you should be able to circumvent this issue by passing `--shm=<a large number>` when launching Docker.

If you're not using Docker (or anything similar) I'll have to take another look at this.

**Comment by Jeffrey-Sardina** [comment]
Thank you very much for your reply!
I am not using Docker, actually; I'm running on bare metal with 16BG RAM / 8 GB graphics memory. The dataset size is 12 GB with 3 partitions. After pre-processing (which includes some compression) the total size of all the training data is 2.2 GB. I am thus not sure why this would be a memory issue, unless PBG is expanding the data size significantly upon loading it. Of course, the presence of the Bus Error means that something there may be going wrong.

**Comment by lw** [comment]
How many entities are you working with? There should be a bunch of `entity_count_foo_42.txt` files in your pre-processed data (for various values of `foo` and `42`), could you look at them and add them all up? (This may give us too big an estimate, but it's a first sanity check). If you take that number, and multiply it by 400 (the dimension you've chosen in your config) and then by 4 (the number of bytes in a float) you'll get the amount of memory needed to store all the embedding tables. How big is that?

**Comment by Jeffrey-Sardina** [comment]
Aha! I have a total of 6 such files, totaling 1GB (the largest of which is 342.5 MB). So that is 1 * 400 * 4 = 1600 GB, well above my running memory. Looks like I'll need to make many more partitions (and / or reduce the number of dimensions); I'll give that a go and let you know what happens.
Thank you again!

**Comment by lw** [comment]
Let me know if it works. Note that the calculation is an overestimate, and a more accurate calculation would the follow: for each entity type `foo`, look at all the `entity_count_foo_i.txt` files (for i = 0, ..., N-1), pick the _two_ largest values and add them together, and then multiply by the dimension * 4. Even after doing that, be sure to keep some "slack" as there's other memory consumed elsewhere, so while this one number is the most important one it does not tell the whole story.

**Comment by Jeffrey-Sardina** [comment]
That did work, thank you!
