### ISSUE TITLE
"ValueError: only one element tensors can be converted to Python scalar" with Affine operator

### ISSUE THREAD

**Issue by Jeffrey-Sardina** [facebookresearch/PyTorch-BigGraph#213]
## Intro
I am posting an error that occured when using the affine operator on a custom dataset. Any help or insight would be greatly appreciated.

## Steps to reproduce
Train and evaluate a model using an affine operator, then run torchbiggraph_export_to_tsv. The code fails with the error "ValueError: only one element tensors can be converted to Python scalars". This does not occur, all else being equal when t5he translation / diagonal operators are used.

I used custom data for this (that is too large to upload); however, I have included all the commands used below for reference. 

## Observed Results
When running the command torchbiggraph_export_to_tsv on a model that was trained using the affine operator, it throws an error when trying to write relation_types_parameters.tsv. This does not happen when using the diagonal or translation operators; all else being equal. Moreover, the issue persisted for various values of the learning rate, loss function, and comparators when the affine operator was used.

The stack trace is shown below:
```
.......
Loading relation types and entities...
Initializing model...
Loading model check point...
Writing entity embeddings...
Reading embeddings for entity type all partition 0 from checkpoint...
Writing embeddings for entity type all partition 0 to output file...
- Processed all 158 entities
Reading embeddings for entity type all partition 1 from checkpoint...
Writing embeddings for entity type all partition 1 to output file...
- Processed all 158 entities
Done exporting entity data to ../copies/.../pbg_out/entity_embeddings.tsv
Writing relation type parameters...
Traceback (most recent call last):
  File "/media/.../pytorch-biggraph-gpu/bin/torchbiggraph_export_to_tsv", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_export_to_tsv')()
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/converters/export_to_tsv.py", line 144, in main
    make_tsv(config, entities_tf, relation_types_tf)
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/converters/export_to_tsv.py", line 44, in make_tsv
    make_tsv_for_relation_types(model, relation_type_storage, relation_types_tf)
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/converters/export_to_tsv.py", line 96, in make_tsv_for_relation_types
    write(
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/converters/export_to_tsv.py", line 24, in write
    outf.write("%s\t%s\n" % ("\t".join(key), "\t".join("%.9f" % x for x in value)))
  File "/media/.../pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/converters/export_to_tsv.py", line 24, in <genexpr>
    outf.write("%s\t%s\n" % ("\t".join(key), "\t".join("%.9f" % x for x in value)))
ValueError: only one element tensors can be converted to Python scalars
```

## Expected Results
I expected the relation_types_parameters.tsv file to be written sucesfully, rather than throwing an error.

## Relevant Code
$CONFIG is the path to my config fiule
$DATA is the name of the dataset I am using
$UUID is just a satring to specify what algorithm parameters I was using

Command to train: (works without error)
```
torchbiggraph_train \
        $CONFIG \
        -p edge_paths=../copies/$DATA/pbg_split/imported/training_data > "../models/${DATA}/${UUID}.trainlog"
```

Command to evaluate: (works without error)
```
torchbiggraph_eval \
        $CONFIG \
        -p edge_paths=../copies/$DATA/pbg_split/imported/validation_data \
        -p relations.0.all_negs=false \
        -p num_batch_negs=500 \
        -p num_uniform_negs=500 > "../models/${DATA}/${UUID}.evallog"
```

Command to write model data: (thrwos the error while writing relation_types_parameters.tsv; entity_embeddings.tsv is written properly)
```
torchbiggraph_export_to_tsv \
    $CONFIG \
    --entities-output ../copies/$DATA/$UUID/pbg_out/entity_embeddings.tsv \
    --relation-types-output ../copies/$DATA/$UUID/pbg_out/relation_types_parameters.tsv
```

Config file:
```
{
    "entities": {
        "all": {
            "num_partitions": 2,
            "featurized": false,
            "dimension": null
        }
    },
    "relations": [
        {
            "name": "all_edges",
            "lhs": "all",
            "rhs": "all",
            "weight": 1.0,
            "operator": "affine",
            "all_negs": false
        }
    ],
    "dimension": 100,
    "init_scale": 0.001,
    "max_norm": null,
    "global_emb": false,
    "comparator": "l2",
    "bias": false,
    "loss_fn": "ranking",
    "margin": 0.1,
    "regularization_coef": 0.0,
    "regularizer": "N3",
    "entity_path": "../copies/bioportal_randsub_200/pbg_split",
    "edge_paths": [
        "../copies/bioportal_randsub_200/pbg_split/imported/training_data"
    ],
    "checkpoint_path": "backup_points/bioportal_randsub_200_2_73",
    "init_path": null,
    "checkpoint_preservation_interval": null,
    "num_epochs": 100,
    "num_edge_chunks": null,
    "max_edges_per_chunk": 1000000000,
    "bucket_order": "inside_out",
    "workers": null,
    "batch_size": 1000,
    "num_batch_negs": 50,
    "num_uniform_negs": 50,
    "disable_lhs_negs": false,
    "disable_rhs_negs": false,
    "lr": 0.01,
    "relation_lr": null,
    "eval_fraction": 0.0,
    "eval_num_batch_negs": 1000,
    "eval_num_uniform_negs": 1000,
    "background_io": false,
    "verbose": 0,
    "hogwild_delay": 2.0,
    "dynamic_relations": true,
    "num_machines": 1,
    "num_partition_servers": -1,
    "distributed_init_method": null,
    "distributed_tree_init_order": true,
    "num_gpus": 1,
    "num_groups_for_partition_server": 16,
    "half_precision": false
}
```

Thank you very much in advance!

**Comment by lw** [comment]
Thanks for reporting! Could you check whether this patch fixes the issue for you? Just apply it and re-export, no need to retrain. Thanks! https://github.com/facebookresearch/PyTorch-BigGraph/pull/214

**Comment by Jeffrey-Sardina** [comment]
Will do! I'm in the middle of training a large dataset, but I'll test the patch out as soon as that is done

**Comment by Jeffrey-Sardina** [comment]
I just pulled the new code and installed it:

```
git clone https://github.com/lw/PyTorch-BigGraph.git
PBG_INSTALL_CPP=1 pip install .
```

However, it's complaining that it cannot understand the key "num_gpus" in my config file, which is present since I am doing GPU training. As a result, it exits with an error before outputting any data. Any idea why this would be?

**Comment by adamlerer** [comment]
I suspect it's because you cloned from @lw 's master branch, which is 70 commits between https://github.com/facebookresearch/PyTorch-BigGraph.git .

If you want to check out @lw 's repo, you can do

```
git clone https://github.com/lw/PyTorch-BigGraph.git
cd PyTorch-BigGraph
git checkout lw:export-D28786238  # added line
PBG_INSTALL_CPP=1 pip install .
```

The more robust way is to checkout the master from https://github.com/facebookresearch/PyTorch-BigGraph.git and apply the patch from @lw

**Comment by Jeffrey-Sardina** [comment]
Thanks! I just ran the test, and yes this patch did fix the output error. Thank you both very much for all the help!
