### ISSUE TITLE
Gives "Unknown key: regularization_coef" while running torchbiggraph_train

### ISSUE THREAD

**Issue by jaiabhayk** [facebookresearch/PyTorch-BigGraph#216]
torchbiggraph_train torchbiggraph/examples/configs/fb15k_config_cpu.py -p edge_paths=data/FB15k/freebase_mtr100_mte100-train_partitioned

Error in the configuration file, aborting.
CRITICAL: Unknown key: regularization_coef

But below command which is end-to-end works fine:
torchbiggraph_example_fb15k

**Comment by adamlerer** [comment]
My guess is you've installed the stable pip version but are running these examples from the repo. Try installing the latest version with 

```
cd PyTorch-BigGraph
pip install .
```

@lw how about we remove the `pip install torchbiggraph` instructions since they're out of date?

**Comment by lw** [comment]
> how about we remove the pip install torchbiggraph instructions since they're out of date?

We could also just release a new version of the PyPI package?

**Comment by jaiabhayk** [comment]
Thanks for the information but if I installed the latest version as mentioned above, I won't work with gpu mode as mentioned in the documentation below

```
PyTorch-BigGraph includes some C++ kernels that are only used for the experimental GPU mode. If you want to use GPU mode, compile the C++ code as follows:

PBG_INSTALL_CPP=1 pip install .
Everything will work identically **except that you won't be able to run GPU training** (torchbiggraph_train_gpu).
```

**Comment by adamlerer** [comment]
You can install it with GPU mode.

```
cd PyTorch-BigGraph
PBG_INSTALL_CPP=1 pip install .
```

**Comment by jaiabhayk** [comment]
But the documentation says it otherwise (which is slightly confusing or I can ignore the documentation ?):

`Everything will work identically except that you won't be able to run GPU training (torchbiggraph_train_gpu).`

**Comment by jaiabhayk** [comment]
Seems working with GPU when installed from the source (may be documentation is old and needs update).

**Comment by adamlerer** [comment]
Oh you're right, the documentation should say "you *will* be able to run GPU training". Thanks for pointing that out, I'll update it.
