### ISSUE TITLE
torchbiggraph_eval: "OSError: [Errno 14] Can't read data"

### ISSUE THREAD

**Issue by Jeffrey-Sardina** [facebookresearch/PyTorch-BigGraph#220]
Hello,

I encountered an issue when running torchbiggraph_eval on one of my datasets, which is descibed below. I would greatly apprecaite any advice you have in regrads to resolving it. Thank you in advance!

## Steps to reproduce

1. Train model (torchbiggraph_train). In this case, I used 5 partitions, which was the minimum I could use without exceeding my computer's memory. This part ran without error
2. Run evaluation on the model results (torchbiggraph_eval, as described in detail below).
3. This resulted in an OSError rather than evaluation statistics

I should also note that I have used this same code on 4 other (smaller) datasets, and in all of those cases it finished evaluation without error. Thus, I am wondering if the size of the data may be a factor here, even though the error semms to suggest corrupted training output files.

## Observed Results
Upon running torchbiggraph_eval (full command shown in the code section below), the evaluator failed with an OSError, saying it could not read the model data. The full stacktrace is shown below:
```
Traceback (most recent call last):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/bin/torchbiggraph_eval", line 11, in <module>
    load_entry_point('torchbiggraph==1.0.1.dev0', 'console_scripts', 'torchbiggraph_eval')()
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 262, in main
    do_eval(config, subprocess_init=subprocess_init)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 239, in do_eval
    for _ in do_eval_and_report_stats(config, model, evaluator, subprocess_init):
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 163, in do_eval_and_report_stats
    embs = load_embeddings(entity, part)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/eval.py", line 114, in load_embeddings
    embs, _ = checkpoint_manager.read(entity, part)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/checkpoint_manager.py", line 297, in read
    embs, serialized_optim_state = self.storage.load_entity_partition(
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/checkpoint_storage.py", line 351, in load_entity_partition
    raise err
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/checkpoint_storage.py", line 344, in load_entity_partition
    embs = load_embeddings(hf, out=out)
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/torchbiggraph/checkpoint_storage.py", line 168, in load_embeddings
    dataset.read_direct(out.numpy())
  File "/media/siothrun/Backup/Thesis/my_code/pytorch-biggraph-gpu/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 973, in read_direct
    self.id.read(mspace, fspace, dest, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 192, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 112, in h5py._proxy.dset_rw
OSError: [Errno 14] Can't read data (file read failed: time = Sat Jun 26 12:43:33 2021
, filename = '/media/siothrun/Backup/Thesis/my_code/backup_points/bioportal_final/embeddings_all_2.v50.h5', file descriptor = 32, errno = 14, error message = 'Bad address', buf = 0x7f1496ee7000, total read size = 1110525376, bytes this sub-read = 1110525376, bytes actually read = 18446744073709551615, offset = 0)
```

## Expected Results
I expected it to output evaluation results rather than throw an error.

## Relevant Code
$DATA is the name of my dataset
$CONFIG is the path to my config file
```
torchbiggraph_eval \
        $CONFIG \
        -p edge_paths=../copies/$DATA/pbg_split/imported/validation_data \
        -p relations.0.all_negs=false \
        -p num_batch_negs=500 \
        -p num_uniform_negs=500
```

Config used (from PBG dump):
```
{
    "entities": {
        "all": {
            "num_partitions": 5,
            "featurized": false,
            "dimension": null
        }
    },
    "relations": [
        {
            "name": "all_edges",
            "lhs": "all",
            "rhs": "all",
            "weight": 1.0,
            "operator": "translation",
            "all_negs": false
        }
    ],
    "dimension": 200,
    "init_scale": 0.001,
    "max_norm": null,
    "global_emb": false,
    "comparator": "l2",
    "bias": false,
    "loss_fn": "ranking",
    "margin": 0.1,
    "regularization_coef": 0.1,
    "regularizer": "N3",
    "entity_path": "../copies/bioportal/pbg_split",
    "edge_paths": [
        "../copies/bioportal/pbg_split/imported/training_data"
    ],
    "checkpoint_path": "backup_points/bioportal_final",
    "init_path": null,
    "checkpoint_preservation_interval": null,
    "num_epochs": 50,
    "num_edge_chunks": null,
    "max_edges_per_chunk": 1000000000,
    "bucket_order": "inside_out",
    "workers": null,
    "batch_size": 1000,
    "num_batch_negs": 500,
    "num_uniform_negs": 100,
    "disable_lhs_negs": false,
    "disable_rhs_negs": false,
    "lr": 0.01,
    "relation_lr": null,
    "eval_fraction": 0.0,
    "eval_num_batch_negs": 1000,
    "eval_num_uniform_negs": 1000,
    "background_io": false,
    "verbose": 0,
    "hogwild_delay": 2.0,
    "dynamic_relations": true,
    "num_machines": 1,
    "num_partition_servers": -1,
    "distributed_init_method": null,
    "distributed_tree_init_order": true,
    "num_gpus": 1,
    "num_groups_for_partition_server": 16,
    "half_precision": false
}
```

**Comment by lw** [comment]
The stack trace shows an error ("bad address", errno 14) when reading the file. Are you able to manually access and read the file? Is that file perhaps located on some network device which might have had issues at that time? Does it succeed if you retry? Or could it perhaps be that your system was running low on memory while reading and that's why it failed?

**Comment by Jeffrey-Sardina** [comment]
I am able to manually access and read the file. To test this, I ran a basic script to scan the h5 file structure (shown below)
```
import h5py
import sys

#From: https://stackoverflow.com/questions/43371438/how-to-inspect-h5-file-in-python
def scan_hdf5(path, recursive=True, tab_step=2):
    def scan_node(g, tabs=0):
        print(' ' * tabs, g.name)
        for k, v in g.items():
            if isinstance(v, h5py.Dataset):
                print(' ' * tabs + ' ' * tab_step + ' -', v.name)
            elif isinstance(v, h5py.Group) and recursive:
                scan_node(v, tabs=tabs + tab_step)
    with h5py.File(path, 'r') as f:
        scan_node(f)

embeddings_h5_file = sys.argv[1] #The name of the file that had been failing for me
scan_hdf5(embeddings_h5_file)
```
Which outputted
```
 /
   - /embeddings
   /optimizer
     - /optimizer/state_dict
```


It's located on an external hard drive, and I've no other access issues with it. I have retired several times, but all times it got the same error. When running it, I see that my RAM never exceeds a few hundred MB (I have a total of 16 GB), and my vRAM remains similarly low--never even reaching 1GB out of 8GB total. In terms of disk memory, I have 400 GB free on the disk I an reading and writing from.

**Comment by lw** [comment]
Your repro scans the "tree" of the HDFS file but it doesn't access the contents: perhaps that part of the file is corrupted and causes an error? Or perhaps the problem is where that data is being read _into_: PBG copies data to shared memory, which is... weird (it has stricter limits than the general system memory, and errors related to it manifest in odd ways). Could you check if your `/dev/shm` is sized too small? I think you should be able to see it through `mount`.

Also, are you only getting that error during evaluation? If you were to restart and continue training on that checkpoint (e.g., by doing one extra epoch) would you get the same error?

**Comment by Jeffrey-Sardina** [comment]
Thanks for your reply! I checked /dev/shm and I see it was as 7.8GB. I tried increasing it to 12GB, which worked. Looks like it was a shared memory issue after all.

Thank you very much!
