### ISSUE TITLE
Getting failures when trying to scale training.

### ISSUE THREAD

**Issue by Jeremy-E-Johnson** [facebookresearch/PyTorch-BigGraph#224]
## Steps to reproduce

I have a data set with about 60 million relations that I would like to run an embedding on. The TDLR is that with a sub-graph of 10M relations, the training goes off without a hitch, but scaling up to even 15M relations is causing issues (bus errors). Once the training call is made, if the number of total nodes is too large, then errors pertaining to not being able to find certain PID files pop up before a final semaphore error and what appears to be a soft-lock of the program. Top shows a split second where there are multiple Python processes all running at once that appear to be spawned to start training before things grind to a halt.

I supposed that memory allocation is the issue at hand, but the max chunk size has been dropped to 100000 and i'm only allowing 4 workers. I would imagine that this server can handle that. Similarly, with these settings, It's my expectation that the memory footprint should not be determined by the total size of the data set, and that 10M and 15M edge data sets would have the same footprint.

For additional context, this is being run in a docker container on a remote Linux server. One possibly relevant note is is that the convert_input_data function does take a long time to complete.

## Observed Results

When training starts, the following errors occur:

  ```
2021-07-22 19:18:25,136 torchbiggraph DEBUG - ( 0 , 0 ): Waiting for workers to perform training
**Bus error (core dumped)**
root@e3cea3c29131:~# 2021-07-22 19:04:40,964 torchbiggraph DEBUG - Flushing one chunk of 6553600 elements to dataset 'rel' of file /data/structure/embeddings/embedding/edges/edges_0_0.tmp.h5Process MemTimer-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/8/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 354, in _init
    self.create_time()
  File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 710, in create_time
    self._create_time = self._proc.create_time()
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1788, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1583, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/dist-packages/memory_profiler.py", line 215, in run
    cur_mem = _get_memory(
  File "/usr/local/lib/python3.8/dist-packages/memory_profiler.py", line 184, in _get_memory
    return tools[backend]()
  File "/usr/local/lib/python3.8/dist-packages/memory_profiler.py", line 128, in ps_util_tool
    process = psutil.Process(pid)
  File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 326, in __init__
    self._init(pid)
  File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 367, in _init
    raise NoSuchProcess(pid, None, msg)
psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 8
/usr/lib/python3.8/multiprocessing/resource_tracker.py:203: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
  ```

## Expected Results

I am expecting training to run. (Not expecting that my parameters will do particularly efficient or good training, though hints on that would be welcome)

## Relevant Code

Here is the final step of data prep and then training:

  ```
entities, rels, entity_paths, edge_paths, _ = parse_config_partial(config)
convert_input_data(entities, rels, entity_paths, edge_paths, [Path(tsv_file.name)], 0, 2, 1)

config_dict = config
        # Checks schema of our configuration object
        try:
            config = ConfigSchema.from_dict(config)
        except Exception as err:
            LOG.error(err)
            raise err

LOG.info("Starting training...")
train(config, subprocess_init=subprocess_init)
  ```

Here is the config definition that I'm using, note that I started without defining values for max_edges_per_chunk and workers,  but started playing around with reducing them from their defaults with the hope that somehow that would stabilize things / keep memory allocation under control.

  ```
config = dict(
        entity_path=str(data_dir),
        edge_paths=[edge_paths], # A single file
        checkpoint_path=checkpoints,

        # Graph structure
        entities={node: {"num_partitions": 1, "featurized": False} for node in node_types}, # approximately 20 different types
        relations=[
            {'name': f"{rel_type[1]}_{rel_type[0]}_{rel_type[2]}", 'lhs': rel_type[1], 'rhs': rel_type[2], "operator": "complex_diagonal"}
            for rel_type in rel_types], # approximately 20 relation types

        dimension=100,
        global_emb=False,
        comparator="dot",

        num_epochs=50,
        num_uniform_negs=1000,
        loss_fn="softmax",
        lr=0.1,
        eval_fraction=0.05,

        max_edges_per_chunk=100000,
        workers=4,
    )
  ```

**Comment by Jeremy-E-Johnson** [comment]
Accidentally posted before finished editing. Will reopen when ready. Apologies...

**Comment by lw** [comment]
> the convert_input_data function does take a long time to complete

This is unfortunately expected, as it's implemented "naively" in Python, without PyTorch acceleration. If it's really a bottleneck and you have means to accelerate it (e.g., a Spark cluster), you could consider writing your own importer.

> scaling up to even 15M relations is causing issues (bus errors). Once the training call is made, if the number of total nodes is too large, then errors pertaining to not being able to find certain PID files pop up before a final semaphore error and what appears to be a soft-lock of the program.

My first guess is that PID files and semaphores are due to processes dying when they shouldn't, thus they're a consequence of the failure but not a cause. The cause seems to be the bus errors (SIGBUS signals). If you search the GitHub issues you'll find it's a common problem caused by there being too little shared memory available on the system. (Shared memory is more constrained than regular memory).

> this is being run in a docker container

This is probably the problem: Docker imposes even stricter limits on the available shared memory. You can control these via the `--shm` flag. Though what we recommend is, in fact, to avoid Docker altogether and run on bare metal.

Hope this helps.

**Comment by Jeremy-E-Johnson** [comment]
This was very helpful. Through increasing shared memory I was able to get this to run.

I greatly appreciate the help!
