### ISSUE TITLE
possible bug in  TSVEdgelistReader

### ISSUE THREAD

**Issue by LeighWeston86** [facebookresearch/PyTorch-BigGraph#227]
[This](https://github.com/facebookresearch/PyTorch-BigGraph/commit/b590de4c61fe7185827e44ad41ef21ddcd8239a8#diff-e83458b445577a73a0313b3bec5409b5420f8127663366c258db7a0fd8440469) PR seems to have broken my job in production.

I am getting an error:

```
File "./__main__.py", line 87, in build_model_files
    TSVEdgelistReader(lhs_col=0, rel_col=1, rhs_col=2),
TypeError: __init__() missing 1 required positional argument: 'weight_col'
```

Do we need to provide these weights now, or should [this](https://github.com/facebookresearch/PyTorch-BigGraph/blob/b590de4c61fe7185827e44ad41ef21ddcd8239a8/torchbiggraph/converters/importers.py#L50) default to `weight_col: Optional[int]=None`? It seems to be checking `words[self.weight_col] if self.weight_word is not None else None` but I don't see where `self.weight_word` is defined.

**Comment by tmarkovich** [comment]
@adamlerer Should we close this?
