### ISSUE TITLE
Question related to pretrained wikidata embeddings

### ISSUE THREAD

**Issue by lynnliu030** [facebookresearch/PyTorch-BigGraph#238]
Hi, I was looking at the wikidata pretrained embeddings in this page https://torchbiggraph.readthedocs.io/en/latest/pretrained_embeddings.html. I'm not quite familiar with the dataset, say now I can get the pretrained embeddings from wikidata_translation_v1_vectors.npy.gz separate them into entity and relation embeddings. How am I able to know the mapping between entity and relation, i.e. which relation can be applied on which entity, and/or the original graph structure in adjacency matrix format?

**Comment by lw** [comment]
If your question is about the Wikidata dataset I suggest you look for information on their website: https://www.wikidata.org/wiki/Wikidata:Main_Page

Our docs should tell you precisely from which snapshot we started and what transformations we applied to it, hence you should be able to retrace all steps.

**Comment by lynnliu030** [comment]
@lw In the website it is said that the pretrained embeddings use “truthy” dump from 2019-03-06, in the RDF NTriples format. And the original file isn’t available anymore on the Wikidata website. How am I able to find the original version of the data is used?

**Comment by lw** [comment]
If the original dump isn't available anymore then that's indeed a problem. I don't think I have the original file still lying around anywhere, sorry...

**Comment by lynnliu030** [comment]
Got it, thanks!
