### ISSUE TITLE
ComplexDiagonalDynamicOperator Error

### ISSUE THREAD

**Issue by aman-sawarn** [facebookresearch/PyTorch-BigGraph#249]
## Steps to reproduce

  1. from torchbiggraph.model import ComplexDiagonalDynamicOperator

  2.  I am unable to import ComplexDiagonalDynamicOperator from torchbiggraph.model, but I can import DotComparator from torchbiggraph.model. Please help me out.
  

## Observed Results

  * ImportError                               Traceback (most recent call last)
/var/folders/mg/8jpsv4t15rq532kwbd9nrtxmjx26v7/T/ipykernel_21573/2960515968.py in <module>
----> 1 from torchbiggraph.model import ComplexDiagonalDynamicOperator

ImportError: cannot import name 'ComplexDiagonalDynamicOperator' from 'torchbiggraph.model' (/opt/anaconda3/lib/python3.9/site-packages/torchbiggraph/model.py)
  

## Expected Results

  * operator = ComplexDiagonalDynamicOperator(400, dynamic_rel_count)
operator.load_state_dict(operator_state_dict)

## Relevant Code

  ```
from torchbiggraph.model import ComplexDiagonalDynamicOperator
  operator = ComplexDiagonalDynamicOperator(400, dynamic_rel_count)
operator.load_state_dict(operator_state_dict)
  ```

**Comment by tmarkovich** [comment]
`ComplexDiagonalDynamicOperator` is in `torchbiggraph.operator`
