### ISSUE TITLE
Save the embeddings after every nth epoch?

### ISSUE THREAD

**Issue by monk1337** [facebookresearch/PyTorch-BigGraph#29]
Hello,

How can I save the embeddings after every nth epoch? suppose I am trying to train model on 1000 epochs but same time I want to save the model/embeddings after every 100 epoch.

How can I do that?

**Comment by lerks** [comment]
What you're asking is being implemented in #24. Please comment there if you have suggestions.

**Comment by monk1337** [comment]
Thank you :)
