### ISSUE TITLE
[Question] Featurized Entities

### ISSUE THREAD

**Issue by ggliem** [facebookresearch/PyTorch-BigGraph#35]
First of all, thank you for this amazing project.

After training different embeddings, I recently started to look at featurized entities. To be more precise, some of the entities in my graph represent text documents and I already trained the corresponding word embeddings. I do know that it’s an advanced feature which hasn’t fully stabilized yet, i.e. that I have to implement my own converter based on the format described in the documentation. However, I was wondering whether you could please share an example of a converter for featurized entities? I think it would be helpful to look at such an example.

Thanks!

**Comment by lerks** [comment]
The documentation tries to describe the format of the edgelist in case of featurized entities: https://torchbiggraph.readthedocs.io/en/latest/featurized_entities.html

In any case, here is an (untested) example script that should convert an edgelist where entities are lists of integers (each integer being a feature) into the correct format for PBG. This doesn't take care of partitioning or of dynamic relations, which work the same for featurized entities as they do for non-featurized ones. Observe that while we store the features in the same order as they appear in the lists, that order has no effect.
```
In [1]: import numpy as np

In [2]: import h5py

In [3]: num_edges = 4

In [4]: lhs_list_of_words = [
    ...:     [5, 8, 2, 4],  # word 0
    ...:     [2, 0, 1],  # word 1
    ...:     [],  # word 2, empty
    ...:     [3, 7],  # word 3
    ...: ]

In [5]: rhs_list_of_words = [
    ...:     [3, 6, 1],  # word 0
    ...:     [0, 2, 2],  # word 1
    ...:     [5, 6],  # word 2
    ...:     [4],  # word 3
    ...: ]

In [6]: list_of_relation_types = [
    ...:     0,
    ...:     2,
    ...:     1,
    ...:     1,
    ...: ]

In [7]: with open("entity_count_lhs.txt", "xt") as f:
    ...:     num_entities = max(max((letter for letter in word), default=0) for word in lhs_list_of_words) + 1
    ...:     f.write(f"{num_entities}")

In [8]: with open("entity_count_rhs.txt", "xt") as f:
    ...:     num_entities = max(max((letter for letter in word), default=0) for word in rhs_list_of_words) + 1
    ...:     f.write(f"{num_entities}")

In [9]: with h5py.File("edges_0_0.h5", "w") as hf:
    ...:     hf.attrs["format_version"] = 1
    ...:     hf["rel"] = np.asarray(list_of_relation_types, dtype=np.int64)
    ...:     hf["lhsd_offsets"] = np.cumsum(np.asarray([0] + [len(word) for word in lhs_list_of_words], dtype=np.int64))
    ...:     hf["lhsd_data"] = np.fromiter((letter for word in lhs_list_of_words for letter in word), dtype=np.int64)
    ...:     hf["lhs"] = np.full(num_edges, fill_value=-1, dtype=np.int64)  # pollute the non-featurized column
    ...:     hf["rhsd_offsets"] = np.cumsum(np.asarray([0] + [len(word) for word in rhs_list_of_words], dtype=np.int64))
    ...:     hf["rhsd_data"] = np.fromiter((letter for word in rhs_list_of_words for letter in word), dtype=np.int64)
    ...:     hf["rhs"] = np.full(num_edges, fill_value=-1, dtype=np.int64)  # pollute the non-featurized column
```

**Comment by ggliem** [comment]
Thanks for sharing this example script.

I have one follow-up question w.r.t. the entity_count_type_part.txt file. The documentation states that it contains the total number of different features. 
Assuming that I have some n-dimensional dense document vectors that represent some entities of a specific entity type (see small example below, dealing with floats). What would be the expected content of the entity_count_lhs.txt file? Am i right to assume that it's the number of distinct values? Just want to get that right.

```
# ...

lhs_list_of_docs = [
        [0.2, 0.5, 0.8],
        [0.3, 0.5, 0.8],
        [0.2, 0.6, 0.2]
]

# ...

with open("entity_count_lhs.txt", "xt") as f:
        num_entities = len(np.unique(lhs_list_of_docs))
        f.write(f"{num_entities}")

# ...
```

**Comment by lerks** [comment]
I'm not sure I understand your example. Your entities (the ones you want to featurize) are D-dimensional vectors of _real numbers_ where, I guess, each dimension represents a feature and each real number is the "score" of that entity w.r.t. that dimension's feature. Is that correct?

In that case, I don't think PBG's "featurized entities" is what you're looking for. Ideally, you'd want D features in total, you'd want to express each entity as containing all the features but you'd want each entity's features to be weighted by the above scores. The last part is what is currently unsupported by PBG. There are no plans to add this support in the short term.

The way I see it is that you actually seem to have already learned an embedding for those entities (the embedding vector being the list of feature scores/weights) and you want to plug this into PBG for further training. If that's the case, take a look at the `init_path` config option which allows you to bootstrap the training with some initial embedding vectors.

**Comment by ggliem** [comment]
Oh alright, got it - thank you! Yes, pretty much - I thought that I could use my d-dimensional word/document embeddings as features based on the following paragraph from the documentation but it seemed to be a misunderstanding from my side.

> For example, entities that represent text documents could have their words as features, i.e., an embedding is learned for each word and the embedding of a document is the average of the embeddings of the words it contains.

Thanks for helping out!

**Comment by lerks** [comment]
To sum it up, if your entities are documents and they contain words, then:
- if you don't have any pre-trained embeddings for either documents or words, use featurized entities (map each distinct word to an integer feature id, and represent the documents as sets of these integers, as I did above) and PBG will learn some embeddings for you;
- if you have pre-trained embeddings for words and want to use them to bootstrap PBG, do exactly as in the previous point but provide the word embeddings you already have using `init_path`;
- if you have pre-trained embeddings for the documents, it's probably easier to forget that they are featurized and just represent each as a "normal" entity and also use `init_path` to inject the embedding you already have for them.

Bear in mind that if an entity type is featurized it must be kept unpartitioned (for now). Other (unfeaturized) entity types in the graph can however still be partitioned. This may limit the usefulness of featurized entity types in a distributed setting.

As there doesn't seem to be further questions, I'm closing this issue. Reopen it if necessary.

**Comment by Ishitori** [comment]
Hi there, I am trying out featurized entities and I wonder, is there a limit on how many edges bucket could there be? Can I create edges_0_1.h5, edges_1_0.h5, edges_1_1.h5 so I could split it between machines?
