### ISSUE TITLE
[ERROR] Parse edge_paths failed

### ISSUE THREAD

**Issue by xavierzw** [facebookresearch/PyTorch-BigGraph#38]
## Environment
python 3.7.1
anaconda、pytorch 1.0.1
torchbiggraph install by 
```bash
pip install torchbiggraph
```

## Steps to reproduce
```bash
torchbiggraph_train \
  examples/configs/fb15k_config.py \
  -p edge_paths=data/FB15k/freebase_mtr100_mte100-train_partitioned
```

## Observed Results

Error in the configuration file, aborting.
edge_paths: Not a list

## Expected Results

succeed to run the training process

**Comment by xavierzw** [comment]
I try to find out why parsing error.

when run
torchbiggraph_train \
  examples/configs/fb15k_config.py \
  -p edge_paths=data/FB15k/freebase_mtr100_mte100-train_partitioned

It will call function override_config_dict (In the file torchbiggraph/config.py) to override edge_paths value.
edge_paths' param_type is typing.List[str]
The condition "isinstance(param_type, type) and issubclass(param_type, list)" is false, therefore edge_paths' value is not list

**Comment by lerks** [comment]
Thanks for reporting this! This seems to be due to a difference between Python 3.6 and 3.7.
```
$ python3.6
>>> from typing import List
>>> isinstance(List[str], type)
True
>>> issubclass(List[str], list)
True
```
```
$ python3.7
>>> from typing import List
>>> isinstance(List[str], type)
False
>>> issubclass(List[str], list)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 1 must be a class
```
It must be said that the Python documentation does warn the the `typing` module is still in development and subject to breaking changes, so this is partly on us. We do however want to support Python 3.7 so I'll try to prepare a fix.
