### ISSUE TITLE
[Question]how to config my model if i parted the point set

### ISSUE THREAD

**Issue by xuchang-x** [facebookresearch/PyTorch-BigGraph#48]
hello, i'd like to ask if i split one type entities like TpyeA into 2 parts, can i just config like this:
```
"entities": {
    "A1": {
      "num_partitions": 1,
      "featurized": false
    },
    "A2": {
      "num_partitions": 2,
      "featurized": false
    },
    "B": {
      "num_partitions": 3,
      "featurized": false
    }
},
"relations": [
    {
      "name": "A1_A1",
      "lhs": "A1",
      "rhs": "A1",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
    {
      "name": "A1_A2",
      "lhs": "A1",
      "rhs": "A2",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
    {
      "name": "A2_A1",
      "lhs": "A2",
      "rhs": "A1",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
    {
      "name": "A1_A1",
      "lhs": "A2",
      "rhs": "A2",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
    {
      "name": "A1_B",
      "lhs": "A1",
      "rhs": "B",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
    {
      "name": "A2_B",
      "lhs": "A2",
      "rhs": "B",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
    {
      "name": "B_A1",
      "lhs": "B",
      "rhs": "A1",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
    {
      "name": "B_A2",
      "lhs": "B",
      "rhs": "A2",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
    {
      "name": "B_B",
      "lhs": "B",
      "rhs": "B",
      "weight": 1.0,
      "operator": "complex_diagonal",
      "all_negs": false
    },
  ],
```
i think the relation like A1_B and A2_B should be the same relation, but i make them separated, i'd like to know if this has any effect to embedding result.

**Comment by lerks** [comment]
Let me start by pointing out that your config would not work because all entity types that appear on the left-hand side of a relation type must be either unpartitioned or partitioned in a single number of partitions. The same holds for the right-hand side. In your case you have entity types A2 and B, split respectively in 2 and 3 partitions, which both appear on both sides.

I understand your question as asking whether one can have multiple relation types sharing the parameters of their operators: that is currently not possible. If you represent them as separate relation types you may end up getting different parameters, with no coupling. However, if your two "subsets" of entities of type A have the same distribution (w.r.t. what is meaningful about their connections to B) then it might just happen that the parameters of the two relation types just end up converging to the same values.

If you explain your overall goal we might be able to help you better.

**Comment by xuchang-x** [comment]
@lerks Thanks a lot for your quick reply.

We have meet a scene have large scale of one type entities, just like we have 10 millions of red point in the following picture and can't operate once through single machine in our situation.
![](https://torchbiggraph.readthedocs.io/en/latest/_images/graph_partitioned.svg)
So we want to partition this set and operate in distributed model.
Could you please give me a example how to config separating the large set into relatively small partitions or just the example config of this picture.
And there is another problem, there is no direction of the orange relation, should i put red type on the left hand or right hand. What should i do if i have edges both from red to yellow and yellow to red.

**Comment by lerks** [comment]
The way you indicate in your configuration file that a certain entity type is partitioned is by setting `num_partitions` to its number of partitions, which will be a value greater than 1. So, for the example in the picture you posted, a possible configuration would be:
```python
{
  "entities": {
    "red": {
      "num_partitions": 3,
    },
    "yellow": {
      "num_partitions": 3,
    },
    "blue": {
      "num_partitions": 1,
    }
  },
  "relations": [
    {
      "name": "orange",
      "lhs": "red",
      "rhs": "yellow",
      "operator": "complex_diagonal",
    },
  ],
}
```
where I assumed that the orange edges go from the red to the yellow. If you have edges in both directions you will have to specify them as two different relation types and call them, for example, "orange_forward" and "orange_backward".

The config tells PBG how to read the data. This means that the data must already be split into those numbers of partitions _before_ calling PBG. If you prepare your input data from a TSV file using `import_from_tsv` this will be handled automatically for you as that command reads the config file. If you're partitioning the data yourself in a custom way you'll need to take care of the partitioning. The format of the data that needs to be produces is described here: https://torchbiggraph.readthedocs.io/en/latest/input_output.html#i-o-format

**Comment by xuchang-x** [comment]
oh, i have a misuderstanding about the config 'num_partitions'. taking it as the id of the partition...
Thanks again for your patient reply, thank you~

**Comment by lerks** [comment]
Glad to hear we've cleared that up! I'm closing this issue since as far as I can tell it's resolved. Please reopen it if there's more.
