### ISSUE TITLE
Does PBG support multi-relation for the same two type entity?

### ISSUE THREAD

**Issue by fly12357** [facebookresearch/PyTorch-BigGraph#74]
PBG is a very convenient tools for graph embedding, thanks for your work.

I have a doubt about the relation between the same two type entities

For example:
Two types entities, one represent user, another represent items.
The relation between user and items can be "click", "pay" .... 

So, I  wonder if the PBG support multi-relation for  the same two type entities?

**Comment by lerks** [comment]
Yes, that is very well supported.

**Comment by fly12357** [comment]
> Yes, that is very well supported.

Thanks for your reply~
