### ISSUE TITLE
How to use edge weights?

### ISSUE THREAD

**Issue by anmol1841** [facebookresearch/PyTorch-BigGraph#76]
## Steps to reproduce

  1. Tried to input the edge weights along with the positive edge tsv file
  2. TSV had edge weights in the 4th column
  3. Any explanation on **how to use edge weights** would be helpful 

## Observed Results

  Error While converting input data

## Relevant Code

  ```
  convert_input_data( args.config, edge_paths, lhs_col=0,rhs_col=2, rel_col=1, weight=3)
  ```

**Comment by lerks** [comment]
We don't currently support weights for individual edges, see #55.

**Comment by anmol1841** [comment]
That was really helpful. Thanks.
