### ISSUE TITLE
Full Release

### ISSUE THREAD

**Issue by agcopenhaver** [facebookresearch/PyTorch-BigGraph#84]
Do you have a timeline for a full release?

**Comment by adamlerer** [comment]
The current released code is a full release. Is there a particular feature that you were looking for that is not released?

**Comment by agcopenhaver** [comment]
I'm trying to add this into the conda-forge, but they typically don't accept dev releases, so I'm running into a problem with that

**Comment by adamlerer** [comment]
Got it. @lerks should answer this question, he's away this week but should respond early next week.

**Comment by agcopenhaver** [comment]
@lerks are you able to provide any insight on this?

**Comment by lerks** [comment]
I was waiting to see if any issues popped up before marking the current version as stable, but in three months nothing really came up, so I think we can go ahead. I'll just make a roundup of the pull request and of the dev branches we have to see if it's worth for any of them to make the cut, and I will try to release v1.0 in a few days.

**Comment by agcopenhaver** [comment]
Awesome! Thanks for the response and the awesome package!

**Comment by agcopenhaver** [comment]
@lerks Any movement on this

**Comment by lerks** [comment]
Sorry to keep you waiting, it turned out there were a couple more things we wanted to get in before a stable release (for example the plugin system for storages that I pushed recently). I'm now waiting a bit to catch bugs in those last few things (I already found a few and will land fixes shortly). After that I hope we're good to go. :)

**Comment by agcopenhaver** [comment]
Thanks for the update!

**Comment by lerks** [comment]
I released yesterday v1.0.0, which should address this issue.
