### ISSUE TITLE
Configs for other datasets in the paper

### ISSUE THREAD

**Issue by Shengyu-Feng** [facebookresearch/PyTorch-BigGraph#86]
Hi, can I find the configs for other datasets like Youtube, Twitter mentioned in the paper? Information like the learning rate for the best result can be quite useful.

**Comment by lerks** [comment]
We managed to recover the configs that I think were used for these results. We haven't re-run the experiments to double-check that they are correct, because we can't find the custom pre- and post-processing code anymore. Let me know if the following isn't enough for you and we can investigate more...

### Twitter
```python
{
        # Graph structure
        "entities": {
            "user": {"num_partitions": 1},
        },
        "relations": [{
            "name": "follow",
            "lhs": "user",
            "rhs": "user",
        }],

        # Scoring model
        "dimension": 500,
        "max_norm": 1.0,
        "global_emb": False,
        "comparator": "dot",

        # Training
        "num_epochs": 10,
        "num_edge_chunks": 10,
        "batch_size": 10000,
        "num_uniform_negs": 0,
        "margin": 0.15,
        "lr": 0.1,

        # Evaluation during training
        "eval_fraction": 0,  # to reproduce results, we need to use all training data
    }
```

### Youtube
```python
{
        # Graph structure
        "entities": {
            "user": {"num_partitions": 1},
        },
        "relations": [{
            "name": "friend",
            "lhs": "user",
            "rhs": "user",
        }],

        # Scoring model
        "dimension": 2048,
        "global_emb": False,

        # Training
        "num_epochs": 100,
        "num_edge_chunks": 2,
        "margin": 0.5,
        "lr": 0.01,

        # Evaluation during training
        "eval_fraction": 0,  # to reproduce results, we need to use all training data
    }
```

**Comment by kadimaolivier** [comment]
Hi , i am getting an importError when i am trying to run the fb15k.py example with Anaconda? may you please  assist me with this

1) ImportError: cannot import name 'add_to_sys_path' from 'torchbiggraph.config' (/home/olivier/anaconda3/lib/python3.7/site-packages/torchbiggraph/config.py

2) is there any step by step guide line to get vectors and calculate similarity between embeddings entity with another data set using pytorchbiggraph tools? 

regards

**Comment by lerks** [comment]
I suspect you are using the config file from a recent version with an older installation of PBG. Could you reinstall and see if that fixes your problem?

Also, if you are having problems, could you open a new issue rather than add a comment in unrelated ones? Thanks.

**Comment by kadimaolivier** [comment]
as you requested me to reinstall the new installation of PBG, i did but i am still getting the same error ; may you please have a look, thanks in advance for your assistance....i also open a new issue on this...thanks...

**Comment by lerks** [comment]
Closing this as there has been no further comments on the original discussions regarding configs for Twitter and Youtube (I'm assuming the original poster was happy with them). Please reopen if needed.
