### ISSUE TITLE
ImportError: cannot import name 'add_to_sys_path' from 'torchbiggraph.config'

### ISSUE THREAD

**Issue by kadimaolivier** [facebookresearch/PyTorch-BigGraph#92]
Hi! when i am trying to run fb15k.py example with anaconda , i am getting this error:

ImportError: cannot import name 'add_to_sys_path' from 'torchbiggraph.config'

as you requested me to reinstall the new installation of PBG, i did but i am still getting the same error ; may you please have a look, thanks in advance for your assistance....

## Steps to reproduce

  1. _____
  2. _____
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.

## Expected Results

  * What did you expect to happen?

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by lerks** [comment]
You will need to provide more information (this is what the template asked you for, please fill it in next time):
- What exact command are you running?
- What is the content of `/home/olivier/anaconda3/lib/python3.7/site-packages/torchbiggraph/examples/configs/fb15K-config.py`?

**Comment by kadimaolivier** [comment]
>     * What exact command are you running?

i am runing the example fb15k.py with **anaconda & spyder**...and i am getting the following error:
importError: cannot import name 'add_to_sys_path' from 'torchbiggraph.config' 

or is there an alternative way to run your example?i would like to understand the code reproduced on fb15k.py

Running this on the terminal  ( torchbiggraph_example_fb15k) it does produce the result but i am interested on understand the conten of your code provided on this particular example....

>     * What is the content of `/home/olivier/anaconda3/lib/python3.7/site-packages/torchbiggraph/examples/configs/fb15K-config.py`?

entity_base = "data/FB15k"


def get_torchbiggraph_config():

    config = dict(
        # I/O data
        entity_path=entity_base,
        edge_paths=[],
        checkpoint_path='model/fb15k',

        # Graph structure
        entities={
            'all': {'num_partitions': 1},
        },
        relations=[{
            'name': 'all_edges',
            'lhs': 'all',
            'rhs': 'all',
            'operator': 'complex_diagonal',
        }],
        dynamic_relations=True,

        # Scoring model
        dimension=400,
        global_emb=False,
        comparator='dot',

        # Training
        num_epochs=50,
        num_uniform_negs=1000,
        loss_fn='softmax',
        lr=0.1,

        # Evaluation during training
        eval_fraction=0,  # to reproduce results, we need to use all training data
    )

    return config

**Comment by lerks** [comment]
I still don't understand how you are running the code. What instructions did you follow? The FB15k example is supposed to be launched with the `torchbiggraph_example_fb15k` command. I'm not sure how you've installed PBG with Anaconda but I believe it should have made that command available to you. I also don't see how Spyder plays a role.

Can you check whether your file `/home/olivier/anaconda3/lib/python3.7/site-packages/torchbiggraph/config.py` contains a function called `add_to_sys_path` on line 456?

**Comment by kadimaolivier** [comment]
> Can you check whether your file `/home/olivier/anaconda3/lib/python3.7/site-packages/torchbiggraph/config.py` contains a function called `add_to_sys_path` on line 456?

yes i did check this what i find: 

def add_to_sys_path(path: str) -> None:
    sys.path.append(path)

>  `torchbiggraph_example_fb15k`

i have tried this on my terminal it works but i would like to lunch it on an IDE

on an IDE is there a way how to lunch pytorchbiggraph example?s

**Comment by lerks** [comment]
If `torchbiggraph_example_fb15k` works then it means your installation is good. I have no idea what your IDE is doing (is it loading the package from a different environment, with an older version installed? is it launching with the root of the repo in the PYTHONPATH and thus importing from the checkout?). We only explicitly support running from the terminal, if you choose to run PBG using any other "custom" way  it's unfortunately up to you to deal with the issues. We just can't do support for anything other than the code we provide ourselves.

**Comment by kadimaolivier** [comment]
> We only explicitly support running from the terminal

ohk thanks for the details  ... i appreciate

**Comment by lerks** [comment]
Closing as there have been no further questions in a month. Please reopen if needed.
