### ISSUE TITLE
[bug] Preparing data script TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by laifi** [facebookresearch/PyTorch-BigGraph#93]
Hello ,
 i get this error each time i try to prepare the edges file 
> Traceback (most recent call last):
>   File "/usr/local/bin/torchbiggraph_import_from_tsv", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/converters/import_from_tsv.py", line 386, in main
>     config_dict = override_config_dict(config_dict, overrides)
>   File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/config.py", line 379, in override_config_dict
>     for override in overrides:
> TypeError: 'NoneType' object is not iterable

 This problem is only from the last commits , as i tried git reset --hard an old commit and now i don't have that error .

**Comment by lerks** [comment]
Thanks for reporting this, it was indeed a bug, which I think I have fixed. Let me know if I missed anything...
