### ISSUE TITLE
How to config PBG with an other dataset

### ISSUE THREAD

**Issue by kadimaolivier** [facebookresearch/PyTorch-BigGraph#96]
Hi, may i have **differents steps to config PBG with another dataset.**
i have tested your example it is working but how can i config PBG with another data which is different of your Dataset.

kindly find the structure of my Data set:

"<101_mile_lake>	<db:location>	""100_mile_house,_british_columbia""."
"<101_mile_lake>	<db:location>	""british_columbia""."
"<101_mile_lake>	<db:name>	""101 mile lake""."
"<101_mile_lake>	<db:point>	""51.6677 121.2934""."
"<101_mile_lake>	<db:wgs84_pos#lat>	""51.6677""."
"<101_mile_lake>	<db:wgs84_pos#long>	""121.2934""."

Thanks.

**Comment by lerks** [comment]
You'll first need to create a config for your data. It looks like it's a knowledge base, just like FB15k, so you can probably bootstrap from that config. You can find that config [here](https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/examples/configs/fb15k_config.py). Copy that, edit the parameter that you want to change (e.g., the dimension, the operator, ...) and save it to a new file called `config.py`.

Your data looks like it's one edge per line, in tokens separated by white space (in order: source entity, relation type, target entity). This is essentially similar to the TSV format we use for FB15k (the name stands for _tab_-separated values but in fact any whitespace works). So, if your dataset is stored in a `edges.txt` file, you can convert it to PBG's own format with
```
torchbiggraph_import_from_tsv --lhs-col=0 --rel-col=1 --rhs-col=2 config.py edges.txt -p entity_path=entities
```
This will create two directories, `entities` and `edges_partitioned`, with the processed input data.

Once you've done that you can proceed with training, using this command:
```
torchbiggraph_train config.py -p entity_path=entities edge_paths=edges_partitioned checkpoint_path=model
```
This will create a directory called `model` and store the checkpoints in it.

Once training is finished, you can convert the trained embeddings back to a text format, using
```
torchbiggraph_export_to_tsv config.py --checkpoint model --dict entities/dictionary.json --entities-output embeddings.txt --relation-types-output parameters.txt
```
This will create two files, `embeddings.txt` with the trained embeddings for the entities and `parameters.txt` for the operator parameters.

Hope this helps!

**Comment by kadimaolivier** [comment]
Hi,

Thanks for your details , indeed it really helped and i am sorted so far and managed to get embeddings.....

great, i appreciate!!!

kind regards

Olivier
