### ISSUE TITLE
Support for MPI backend?

### ISSUE THREAD

**Issue by currymj** [facebookresearch/PyTorch-BigGraph#98]
I am trying to run distributed PBG on a cluster that uses a Slurm scheduler, but keep getting a `RuntimeError: No route to host`, causing various processes (lock and parameter servers) to crash.

While trying to narrow this down into a reproducible example, it seemed like it might be possible to avoid this problem by using the MPI instead of Gloo backend. However, there's no obvious way to choose a different backend -- it looks like Gloo might be hardcoded.

It seems like there probably isn't much of a performance advantage to using MPI due to the way PBG works (very little communication among the workers). But it conceivably might be a workaround to a problem in this case -- is there somewhere in the configuration file or command line options to set the backend?

**Comment by adamlerer** [comment]
I don’t think we currently have the backend exposed, but you can easily
just change it in the code (just search for “gloo”and change to “mpi”). If
you want to plumb that in as an option to the config and send it in as a
pr, we’d happily accept it!

**Comment by lerks** [comment]
@currymj Any update on this? Have you tried patching the code to replace Gloo with MPI? The line, if you're still looking for it, is:
https://github.com/facebookresearch/PyTorch-BigGraph/blob/23e3ff2b5736c9a30e585e209d7ffe171d7106cd/torchbiggraph/distributed.py#L75
Having an answer to this question may also help us debug #99

**Comment by currymj** [comment]
The MPI backend requires building PyTorch from source, which is also turning out to be difficult to do on this cluster, for unclear reasons that don't show up on Google or in the GitHub issues. So I unfortunately can't try out MPI until I figure out how to get PyTorch to build.
